#!/usr/bin/env python3
"""Dependency-free bilingual static publishing for GitHub Pages."""
import json, re, shutil, html
from pathlib import Path
from datetime import date
from content import CLASSES, GUIDES, GLOSSARY, SOURCES

ROOT=Path(__file__).parent
CONFIG=json.loads((ROOT/'site.json').read_text())
OUT=ROOT/'docs'
SITE=CONFIG['url'].rstrip('/')
from urllib.parse import urlparse
BASE=urlparse(SITE).path.rstrip('/')+'/'
REPO=CONFIG['repository']
REVIEWED=CONFIG['reviewed']
ads=CONFIG['adsense']
valid_pub=bool(re.fullmatch(r'ca-pub-\d{16}',ads['publisher_id']))
if ads['enabled'] and not (valid_pub and ads['consent_reviewed'] and re.fullmatch(r'\d+',ads['slot'])):
    raise SystemExit('Ads require a valid publisher ID, ad slot and completed consent/privacy review. See OPERATIONS.md.')
E=lambda s:html.escape(str(s),quote=True)
search_index=[]
pages=[]
L=0
LANG='en'
def t(en,ko):return (en,ko)[L]
def pair(v):return v[L]
def path(sub='',lang=None):
    lang=lang or LANG
    return ('ko/' if lang=='ko' else '')+sub
def href(sub='',lang=None):return BASE+path(sub,lang)
def link(sub,label,css='',lang=None):return f'<a href="{href(sub,lang)}" class="{css}">{label}</a>'
def icon(name,css='icon'):
    return f'<svg class="{css}" aria-hidden="true" viewBox="0 0 48 48"><use href="{BASE}assets/icons.svg#{name}"/></svg>'
def button(sub,label,primary=False):return link(sub,f'{label}<span class="arrow" aria-hidden="true">↗</span>','btn'+(' primary' if primary else ''))
def brand():return f'<a class="brand" href="{href()}" aria-label="Daeva Atlas home">{icon("atlas","brandmark")}<span><strong>DAEVA ATLAS</strong><small>THE AION 2 FIELD GUIDE</small></span></a>'
def role(r):return {'damage':t('Damage','공격'),'tank':t('Tank','탱커'),'healer':t('Healer','회복'),'support':t('Support','지원')}[r]
def combat_range(r):return t('Melee','근접') if r=='melee' else t('Ranged','원거리')
def adslot():
    if not ads['enabled']:return ''
    return f'<aside class="ad-slot" aria-label="Advertisement"><span>ADVERTISEMENT</span><ins class="adsbygoogle" style="display:block" data-ad-client="{E(ads["publisher_id"])}" data-ad-slot="{E(ads["slot"])}" data-ad-format="auto" data-full-width-responsive="true"></ins><script>(adsbygoogle=window.adsbygoogle||[]).push({{}});</script></aside>'
def header(sub,active):
    nav=[('guides/',t('Guides','공략'),'guides'),('classes/',t('Classes','직업'),'classes'),('tools/planner/',t('My planner','내 플래너'),'planner'),('glossary/',t('KR glossary','한영 용어집'),'glossary')]
    return f'''<a class="skip" href="#main">{t('Skip to content','본문으로 건너뛰기')}</a>
<div class="topline"><div class="wrap"><span><span class="dot"></span>{t('An independent guide to AION 2','아이온 2 독립 공략 가이드')}</span><span class="top-secondary">{t('English insight. Korean context.','영어로 만나는 공략. 한국 정보의 맥락.')}</span>{link('about/',t('Our editorial approach ↗','편집 원칙 ↗'))}</div></div>
<header class="masthead"><div class="wrap nav">{brand()}<nav id="main-nav" class="navlinks" aria-label="{t('Main navigation','주 메뉴')}">{''.join(link(p,n,'active' if active==a else '') for p,n,a in nav)}</nav><div class="navtools"><a class="search-link" href="{href('search/')}" aria-label="{t('Search guides','공략 검색')}">{icon('search')}</a>{link(sub,'한국어' if LANG=='en' else 'EN','lang',lang='ko' if LANG=='en' else 'en')}</div><button class="menu" data-menu aria-controls="main-nav" aria-expanded="false">{t('Menu','메뉴')}</button></div></header>'''
def footer():return f'''<footer class="footer"><div class="wrap"><div class="footer-main"><div>{brand()}<p class="footer-desc">{t('Practical reading, thoughtful choices, and a little less guesswork in Atreia.','아트레이아에서 필요한 정보를 읽고, 자신에게 맞는 선택을 할 수 있도록.')}</p></div><nav class="footer-links" aria-label="{t('Footer','하단 메뉴')}">{link('about/',t('About & editorial','소개·편집 원칙'))}{link('sources/',t('Sources & updates','출처·업데이트'))}{link('contact/',t('Contact & corrections','문의·수정 요청'))}{link('privacy/',t('Privacy & local data','개인정보·기기 저장'))}{link('terms/',t('Terms & disclaimer','이용 안내·면책'))}<a href="{REPO}">GitHub ↗</a></nav></div><div class="footer-bottom"><p>© 2026 Daeva Atlas · {t('Independent fan publication. Not affiliated with NC. AION 2 and related marks belong to their owners.','독립 팬 프로젝트이며 NC와 제휴 관계가 없습니다. 아이온 2 관련 상표는 각 권리자에게 있습니다.')}</p><p>{t('EN / KO · Built for the open web','EN / KO · 열린 웹을 위한 가이드')}</p></div></div></footer>'''
def write(sub,title,description,content,active='',article=False,index=True):
    route=path(sub)
    canonical=SITE+'/'+route
    en=SITE+'/'+path(sub,'en');ko=SITE+'/'+path(sub,'ko')
    meta={'@context':'https://schema.org','@type':'Article' if article else 'WebPage','headline':title,'name':title,'description':description,'url':canonical,'inLanguage':LANG}
    if article:meta.update({'author':{'@type':'Organization','name':'Daeva Atlas editorial','url':SITE+'/about/'},'publisher':{'@type':'Organization','name':'Daeva Atlas'},'datePublished':REVIEWED,'dateModified':REVIEWED})
    adhead=f'<meta name="google-adsense-account" content="{E(ads["publisher_id"])}">' if valid_pub else ''
    if ads['enabled']:adhead+=f'<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client={E(ads["publisher_id"])}" crossorigin="anonymous"></script>'
    output=f'''<!doctype html><html lang="{LANG}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} | Daeva Atlas</title><meta name="description" content="{E(description)}"><meta name="theme-color" content="#192e33"><meta name="color-scheme" content="light"><meta name="robots" content="{'index,follow' if index else 'noindex,follow'}"><link rel="canonical" href="{canonical}"><link rel="alternate" hreflang="en" href="{en}"><link rel="alternate" hreflang="ko" href="{ko}"><link rel="alternate" hreflang="x-default" href="{en}"><meta property="og:type" content="{'article' if article else 'website'}"><meta property="og:title" content="{E(title)}"><meta property="og:description" content="{E(description)}"><meta property="og:url" content="{canonical}"><meta property="og:site_name" content="Daeva Atlas"><meta name="referrer" content="strict-origin-when-cross-origin"><link rel="icon" type="image/svg+xml" href="{BASE}assets/favicon.svg"><link rel="stylesheet" href="{BASE}assets/style.css"><script defer src="{BASE}assets/app.js"></script><script type="application/ld+json">{json.dumps(meta,ensure_ascii=False).replace('<',chr(92)+'u003c')}</script>{adhead}</head><body data-base="{BASE}">{header(sub,active)}<main id="main">{content}</main>{footer()}</body></html>'''
    dest=OUT/route/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(output)
    if index:pages.append(canonical)
def pagehead(title,desc,tag='',crumb=''):
    return f'<div class="page-head"><div class="breadcrumbs">{link("",t("Home","홈"))}<span>/</span><span>{E(crumb or title)}</span></div><h1>{title}</h1><p class="lead">{desc}</p>{f"<span class=\"tag\">{tag}</span>" if tag else ""}</div>'
def classcard(c):return f'''<a href="{href('classes/'+c['id']+'/')}" class="class-card" style="--class-color:{c['color']}" data-class-card data-role="{c['role']}"><span class="mini-arrow" aria-hidden="true">↗</span>{icon(c['icon'],'class-symbol')}<h3>{c['ko'] if L else c['en']}</h3><p>{role(c['role'])} · {combat_range(c['range'])}</p></a>'''
def guidecard(g):return f'''<a class="guide-card" href="{href('guides/'+g['slug']+'/')}"><div><span class="tag">{pair(g['category'])}</span></div><h2>{pair(g['title'])}</h2><p>{pair(g['description'])}</p><span class="small muted">{g['minutes']} {t('min read','분 읽기')} <span aria-hidden="true">↗</span></span></a>'''
def sourcelist(keys):
    return '<div class="sources"><strong>'+t('Sources & scope','출처와 적용 범위')+'</strong><ul>'+''.join(f'<li><a href="{E(SOURCES[k]["url"])}" rel="noopener">{E(SOURCES[k]["title"])}</a><span class="source-note">{E(SOURCES[k]["scope"])} · {E(SOURCES[k]["note"])}</span></li>' for k in keys)+'</ul><p class="small muted">'+t('Source review: October 7, 2026. Advice and practice exercises are original editorial analysis, not live gameplay measurements.','출처 검토: 2026년 10월 7일. 조언과 연습 방법은 편집상 분석이며 실제 플레이 측정 결과가 아닙니다.')+'</p></div>'

def home():
    art=(ROOT/'assets/atlas-art.svg').read_text()
    g=GUIDES[0]
    rows=''.join(f'<a class="article-row" href="{href("guides/"+x["slug"]+"/")}"><span class="num">0{i+2}</span><div><span class="tag">{pair(x["category"])}</span><h3>{pair(x["title"])}</h3><p>{x["minutes"]} {t("min read","분 읽기")} · {t("Editorial guide","에디토리얼 가이드")}</p></div><span aria-hidden="true">↗</span></a>' for i,x in enumerate([GUIDES[1],GUIDES[2],GUIDES[3]]))
    body=f'''<div class="wrap"><section class="hero"><div><div class="eyebrow">{t('Your next chapter in Atreia','아트레이아에서 시작하는 다음 여정')}</div><h1>{t('Less guesswork.<br>More <em>adventure.</em>','더 명확한 선택.<br>더 즐거운 <em>모험.</em>')}</h1><p class="intro">{t('Find your class. Understand the Korean context. Make your next session count. An independent AION 2 field guide for global players.','나에게 맞는 직업을 찾고, 한국과 글로벌 정보의 맥락을 이해하세요. 다음 플레이를 돕는 독립 아이온 2 공략집입니다.')}</p><div class="hero-actions">{button('guides/first-session/',t('Start your journey','처음 시작하기'),True)}{button('tools/compare/',t('Compare classes','직업 비교하기'))}</div><div class="hero-note"><span>↗ {t('Source-linked guides','출처가 있는 정보')}</span><span>↗ {t('EN + 한국어','한국어 + English')}</span><span>↗ {t('Free planning tools','무료 플레이 도구')}</span></div></div><div class="hero-art">{art}<div class="art-frame"></div><div class="art-label">THE FIELD NOTES · VOL. 01<small>{t('Original atlas illustration · not game footage','오리지널 아틀라스 일러스트 · 게임 화면 아님')}</small></div><span class="art-coordinate">ATREIA / A NEW PERSPECTIVE</span></div></section>
<div class="notice-strip"><span class="tag">{t('Field note','가이드 노트')}</span><span>{t('Global and Korean information can differ. Every guide keeps its context visible.','글로벌과 한국 정보는 다를 수 있습니다. 공략의 적용 범위를 함께 확인하세요.')}</span>{link('guides/read-korean-guides/',t('Read the guide <span class="arrow">↗</span>','활용법 읽기 <span class="arrow">↗</span>'))}</div>
<section class="section"><div class="section-heading"><div><div class="eyebrow">{t('A good place to begin','첫 모험을 위한 준비')}</div><h2>{t('Find your footing.','시작을 탄탄하게.')}</h2></div>{link('guides/',t('All guides ↗','전체 공략 ↗'),'text-link')}</div><div class="feature-grid"><a class="feature-card" href="{href('guides/'+g['slug']+'/')}"><div><span class="tag">{t('The class selection guide','직업 선택 가이드')}</span></div><h3>{t('Your class should<br>feel like you.','내 플레이에 맞는<br>직업을 찾아보세요.')}</h3><p>{pair(g['description'])}</p><span class="text-link">{t('Find your playstyle ↗','플레이스타일 찾기 ↗')}</span>{icon('atlas','decor')}</a><div class="article-list">{rows}</div></div></section></div>
<section class="panel-section section"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">{t('Eight ways to begin','여덟 가지 플레이스타일')}</div><h2>{t('Find your calling.','당신의 역할은?')}</h2></div>{link('classes/',t('Explore the classes ↗','직업 살펴보기 ↗'),'text-link')}</div><div class="class-grid">{''.join(classcard(c) for c in CLASSES)}</div><p class="section-caption">{t('Playstyle orientation, not a tier list. Current skills and balance should be checked in your regional client.','플레이스타일 분류이며 티어표가 아닙니다. 현재 스킬과 밸런스는 자신의 지역 클라이언트에서 확인하세요.')}</p></div></section>
<div class="wrap"><section class="section"><div class="section-heading"><div><div class="eyebrow">{t('Keep these close','모험에 도움이 되는 도구')}</div><h2>{t('A little help, every session.','매번의 플레이를 가볍게.')}</h2></div></div><div class="tool-strip"><a class="tool-card" href="{href('tools/planner/')}"><span class="tool-icon">{icon('check')}</span><div><h3>{t('Your session planner','나의 플레이 플래너')}</h3><p>{t('One clear goal. A checklist that stays with you. Saved in your browser, ready when you return.','오늘의 목표를 정하고 할 일을 체크하세요. 같은 브라우저로 돌아오면 이어서 볼 수 있습니다.')}</p></div><span class="arrow">↗</span></a><a class="tool-card" href="{href('glossary/')}"><span class="tool-icon">{icon('book')}</span><div><h3>{t('Lost in translation?','용어가 헷갈리나요?')}</h3><p>{t('Korean class names and common guide terminology, with the context a literal translation misses.','한국어·영어 직업명과 공략에서 자주 만나는 용어를 맥락과 함께 확인하세요.')}</p></div><span class="arrow">↗</span></a></div><div class="editorial-bar"><h3>{t('Know what you’re reading.','어떤 정보인지 분명하게.')}</h3><p>{t('We separate official facts from editorial advice. Sources, dates and regional context come with the guide—so you can make your own call.','공식 정보와 플레이 조언을 구분합니다. 출처, 날짜, 지역 맥락을 함께 제공해 스스로 판단할 수 있도록 돕습니다.')}</p>{link('about/',t('Our approach ↗','편집 원칙 ↗'),'text-link')}</div></section></div>'''
    write('',t('AION 2 guides, class comparisons & Korean glossary','아이온 2 공략·직업 비교·한영 용어집'),t('Independent AION 2 guides for global players. Compare classes, understand Korean guides, and plan your next session.','글로벌 유저를 위한 아이온 2 독립 공략. 직업을 비교하고 한국 공략의 맥락을 이해하며 다음 플레이를 준비하세요.'),body)

def guides():
    write('guides/',t('AION 2 field guides','아이온 2 공략 모음'),t('Practical reading for your first character, group play, upgrades and Korean-to-global context.','첫 캐릭터, 파티 플레이, 성장 판단과 한국·글로벌 맥락을 위한 가이드.'),f'<div class="wrap">{pagehead(t("The field guides.","모험을 위한 공략집."),t("One useful question at a time. Choose where your next session needs a little clarity.","한 번에 질문 하나씩. 다음 플레이에 도움이 필요한 주제를 골라보세요."))}<div class="guide-grid">{"".join(guidecard(g) for g in GUIDES)}</div></div>','guides')
    for g in GUIDES:
        sub='guides/'+g['slug']+'/'
        toc=''.join(f'<li><a href="#section-{i+1}">{pair(h)}</a></li>' for i,(h,p) in enumerate(g['sections']))
        body=''.join(f'<section id="section-{i+1}"><h2>{pair(h)}</h2><p>{pair(p)}</p></section>'+ (adslot() if i==2 else '') for i,(h,p) in enumerate(g['sections']))
        related='tools/compare/' if g['slug']=='choose-your-class' else 'glossary/' if g['slug']=='read-korean-guides' else 'tools/planner/'
        relatedlabel=t('Put the guide into practice →','관련 도구로 실천해보기 →')
        content=f'''<div class="wrap">{pagehead(pair(g['title']),pair(g['description']),pair(g['scope']),t('Guides','공략'))}<div class="meta" style="margin:0 0 35px"><span>Daeva Atlas editorial</span><span>{t('Reviewed','검토')} {REVIEWED}</span><span>{g['minutes']} {t('min read','분 읽기')}</span></div><div class="article-layout"><aside class="toc"><strong>{t('In this guide','이 글의 순서')}</strong><ol>{toc}</ol></aside><article class="article-body">{body}{sourcelist(g['sources'])}<div class="related">{button(related,relatedlabel,True)}</div></article></div></div>'''
        write(sub,pair(g['title']),pair(g['description']),content,'guides',True)
        search_index.append({'lang':LANG,'path':path(sub),'title':pair(g['title']),'description':pair(g['description']),'category':pair(g['category']),'keywords':' '.join(pair(h)+' '+pair(p) for h,p in g['sections'])})

def classes():
    filters=''.join(f'<button class="filter" data-class-filter="{r}" aria-pressed="{str(r=="all").lower()}">{t("All classes","전체 직업") if r=="all" else role(r)}</button>' for r in ['all','damage','tank','healer','support'])
    content=f'''<div class="wrap">{pagehead(t('Find your calling.','내 역할을 찾아보세요.'),t('Start with a role and a combat style. These are qualitative playstyle guides, not current damage rankings.','역할과 전투 스타일로 시작하세요. 플레이스타일 안내이며 현재 피해량 순위는 아닙니다.'))}<div class="filterbar">{filters}</div><p class="sr-only" data-filter-status role="status"></p><div class="class-grid">{''.join(classcard(c) for c in CLASSES)}</div><div class="callout"><strong>{t('A better question than “Which is S-tier?”','S티어가 무엇인지보다 먼저')}</strong><p>{t('Which decisions do you want to make in every fight? Compare two classes side by side, then test your shortlist in the current client.','매 전투에서 어떤 판단을 하고 싶은가요? 두 직업을 나란히 비교한 뒤 현재 클라이언트에서 후보를 시험해보세요.')}</p></div><p style="margin-bottom:60px">{button('tools/compare/',t('Open class comparison','직업 비교 열기'),True)}</p></div>'''
    write('classes/',t('AION 2 classes and playstyles','아이온 2 직업과 플레이스타일'),t('Explore Gladiator, Templar, Assassin, Ranger, Sorcerer, Spiritmaster, Cleric and Chanter.','검성·수호성·살성·궁성·마도성·정령성·치유성·호법성의 방향을 비교하세요.'),content,'classes')
    for c in CLASSES:
        name=c['ko'] if L else c['en'];sub='classes/'+c['id']+'/'
        title=t(c['en']+' playstyle guide',name+' 플레이스타일 가이드')
        sections=[(t('Why put this class on your shortlist?','이 직업을 후보로 생각한다면'),pair(c['fit'])),(t('The trade-off to consider','함께 고려할 점'),pair(c['trade'])),(t('Your first practice exercise','첫 번째 연습'),pair(c['practice'])),(t('How to compare fairly','공정하게 비교하는 방법'),t('Use similar equipment and the same available encounter when comparing classes. Repeat more than one attempt. Record control comfort, missed mechanics and whether the playstyle stays enjoyable after a mistake. Your favourite activity and available play time matter more than an unlabelled tier score.','장비와 전투 조건을 비슷하게 맞추고 여러 번 비교하세요. 조작감, 놓친 패턴, 실수 이후에도 즐겁게 이어갈 수 있는지 기록해보세요. 조건 없는 티어 점수보다 자주 하는 콘텐츠와 실제 플레이 시간이 중요합니다.')),(t('Build and version context','세팅과 버전의 맥락'),t('This profile describes a playstyle; it does not prescribe a rotation, skill build or stat priority. Before following a detailed setup, match its region, date, activity and equipment assumptions to your character. Do not infer a global skill value from a Korean clip or an early design announcement.','이 글은 플레이스타일을 설명하며 스킬 연계, 스킬 구성, 능력치 우선순위를 지정하지 않습니다. 자세한 세팅을 따르기 전 지역, 날짜, 콘텐츠, 장비 전제가 자신의 캐릭터와 맞는지 확인하세요. 한국 영상이나 초기 개발 발표의 수치를 글로벌 수치로 단정하지 마세요.'))]
        content=f'''<div class="wrap">{pagehead(title,pair(c['line']),t('Playstyle orientation · Editorial','플레이스타일 안내 · 편집 분석'),t('Classes','직업'))}<div class="article-layout"><aside class="toc"><strong>{t('Class profile','직업 프로필')}</strong><p>{role(c['role'])} / {combat_range(c['range'])}</p>{link('tools/compare/',t('Compare classes ↗','직업 비교 ↗'),'text-link')}</aside><article class="article-body"><div class="class-detail-hero" style="color:{c['color']}">{icon(c['icon'],'class-symbol')}<div><h2>{name}</h2><p>{c['en'] if L else c['ko']} · {pair(c['identity'])}</p></div></div>{''.join(f'<section><h2>{h}</h2><p>{p}</p></section>' for h,p in sections)}{sourcelist(['core','official'])}<div class="related">{button('guides/choose-your-class/',t('The class selection guide','직업 선택 가이드'),True)}</div></article></div></div>'''
        write(sub,title,pair(c['fit']),content,'classes',True)
        search_index.append({'lang':LANG,'path':path(sub),'title':title,'description':pair(c['identity']),'category':t('Class guide','직업 안내'),'keywords':c['en']+' '+c['ko']+' '+role(c['role'])+' '+pair(c['fit'])})

def compare():
    options=lambda selected:''.join(f'<option value="{c["id"]}"{" selected" if c["id"]==selected else ""}>{c["ko"] if L else c["en"]}</option>' for c in CLASSES)
    content=f'''<div class="wrap">{pagehead(t('Two classes. A clearer choice.','두 직업을 나란히 비교.'),t('Compare the role, trade-offs and first practice exercise for your shortlist. No invented scores.','역할, 고려할 점, 첫 연습 방법을 비교하세요. 근거 없는 점수는 사용하지 않습니다.'))}<div class="compare-selects"><label class="field" for="class-a">{t('First class','첫 번째 직업')}<select id="class-a">{options('templar')}</select></label><label class="field" for="class-b">{t('Second class','두 번째 직업')}<select id="class-b">{options('gladiator')}</select></label></div><div class="comparison" data-comparison></div><p class="status" data-compare-status role="status"></p><div style="margin:20px 0 40px"><button class="btn" data-share>{t('Copy comparison link ↗','비교 링크 복사 ↗')}</button><span class="share-status" data-share-status role="status"></span></div><noscript><p>{t('JavaScript is needed for the comparison tool. All class profiles can be read below.','비교 도구에는 자바스크립트가 필요합니다. 아래 직업별 글에서 내용을 볼 수 있습니다.')}</p><div class="class-grid">{''.join(classcard(c) for c in CLASSES)}</div></noscript><div class="callout"><p>{t('These are editorial playstyle profiles. They are not measured DPS, current tier rankings, or a guarantee about endgame viability.','편집한 플레이스타일 프로필입니다. 실측 DPS, 현재 티어 순위, 최종 콘텐츠 성능을 보장하는 자료는 아닙니다.')}</p></div>{sourcelist(['core','official'])}<div style="height:35px"></div><script id="class-data" type="application/json">{json.dumps(CLASSES,ensure_ascii=False).replace('<',chr(92)+'u003c')}</script></div>'''
    write('tools/compare/',t('AION 2 class comparison tool','아이온 2 직업 비교 도구'),t('Compare two AION 2 class playstyles side by side and share your shortlist.','아이온 2의 두 직업 플레이스타일을 나란히 비교하고 링크를 공유하세요.'),content,'classes')

def glossary():
    rows=''.join(f'<tr data-term><td lang="ko"><strong>{E(kr)}</strong></td><td lang="en">{E(en)}</td><td><small>{E(note)}</small></td></tr>' for kr,en,note in GLOSSARY)
    content=f'''<div class="wrap">{pagehead(t('A little less lost in translation.','공략 용어, 이제 헷갈리지 않게.'),t('Korean class names and common community terms. Match skill and item names to your current client before copying a build.','한국어 직업명과 커뮤니티 용어를 영어와 함께 확인하세요. 스킬·아이템 이름은 현재 클라이언트와 대조해야 합니다.'))}<label class="sr-only" for="glossary-search">{t('Search Korean or English terms','한국어·영어 용어 검색')}</label><div class="searchbox">{icon('search')}<input id="glossary-search" data-glossary-search type="search" placeholder="{t('Try 검성, tank, cooldown…','검성, tank, cooldown…')}" autocomplete="off"></div><p class="small muted" data-glossary-count role="status">32 {t('terms','개 용어')}</p><p class="no-results" data-glossary-empty hidden>{t('No matching terms. Try a shorter word.','일치하는 용어가 없습니다. 더 짧은 단어로 검색해보세요.')}</p><div class="table-wrap"><table><thead><tr><th>{t('Korean','한국어')}</th><th>{t('English','영어')}</th><th>{t('Context','맥락')}</th></tr></thead><tbody>{rows}</tbody></table></div></div>'''
    write('glossary/',t('AION 2 Korean–English glossary','아이온 2 한국어·영어 용어집'),t('Search Korean AION 2 class names, combat terms and common guide vocabulary.','아이온 2 한국어·영어 직업명, 전투 용어, 공략 표현을 검색하세요.'),content,'glossary')
    search_index.append({'lang':LANG,'path':path('glossary/'),'title':t('Korean–English glossary','한국어·영어 용어집'),'description':t('32 class names and useful community terms.','직업명과 커뮤니티 용어 32개.'),'category':t('Tool','도구'),'keywords':' '.join(' '.join(row) for row in GLOSSARY)})

def planner():
    content=f'''<div class="wrap">{pagehead(t('Make room for a good session.','즐거운 플레이를 위한 작은 계획.'),t('One goal is a good start. Keep your own checklist, then leave yourself a clear next step.','목표 하나면 충분합니다. 나의 할 일을 기록하고 다음 접속 때 이어가세요.'))}<div class="planner-layout" data-planner><section class="planner-panel"><span class="eyebrow">{t('Your field notes','나의 모험 메모')}</span><h2>{t('Today’s checklist','오늘의 체크리스트')}</h2><p class="small muted">{t('Personal tasks, not an official daily or weekly activity list. Nothing resets automatically.','개인 할 일이며 공식 일일·주간 활동 목록이 아닙니다. 자동 초기화되지 않습니다.')}</p><p class="small" data-progress-text aria-live="polite"></p><div class="progress-track" aria-hidden="true"><div class="progress-fill" data-progress-fill></div></div><div data-task-list></div><form class="task-form" data-task-form><label class="sr-only" for="new-task">{t('Add a personal task','개인 할 일 추가')}</label><input id="new-task" class="task-input" maxlength="160" required placeholder="{t('One thing to work on…','이번에 할 일 하나…')}"><button class="btn primary" type="submit">{t('Add +','추가 +')}</button></form><div class="planner-actions"><button class="btn" data-reset-checks>{t('Uncheck all','전체 체크 해제')}</button><button class="btn" data-export>{t('Export list ↓','목록 내보내기 ↓')}</button></div><p class="status" data-planner-status role="status"></p></section><aside class="planner-panel"><span class="eyebrow">{t('Set a gentle boundary','시간을 가볍게 정해보세요')}</span><h2>{t('How long do you have?','얼마나 플레이할까요?')}</h2><p class="small muted">{t('An editable mindset, not an estimate of dungeon duration. Choose your own activity for the middle block.','던전 소요 시간의 예측이 아닙니다. 가운데 시간에 할 활동을 직접 정하세요.')}</p><div class="budget-choice">{''.join(f'<button class="filter" data-budget="{n}" aria-pressed="false">{n} {t("min","분")}</button>' for n in [30,60,90])}</div><div data-session-plan aria-live="polite"></div><div class="callout"><p>{t('Finish by writing one sentence: “Next time, I will…” A clear stopping point helps you return without rebuilding the whole plan.','마지막에는 “다음에는…”으로 시작하는 문장을 하나 남겨보세요. 다시 들어왔을 때 계획을 처음부터 세우지 않아도 됩니다.')}</p></div></aside></div><noscript><p>{t('The interactive planner needs JavaScript. You can use the first-session guide without it.','인터랙티브 플래너에는 자바스크립트가 필요합니다. 첫 접속 가이드는 자바스크립트 없이도 읽을 수 있습니다.')}</p></noscript></div>'''
    write('tools/planner/',t('AION 2 personal session planner','아이온 2 개인 플레이 플래너'),t('A browser-saved personal checklist and a 30, 60 or 90 minute session plan.','브라우저에 저장되는 개인 체크리스트와 30·60·90분 플레이 계획.'),content,'planner')
    search_index.append({'lang':LANG,'path':path('tools/planner/'),'title':t('Your session planner','나의 플레이 플래너'),'description':t('Save a personal checklist and export your plan.','개인 체크리스트를 저장하고 계획을 내보내세요.'),'category':t('Tool','도구'),'keywords':'checklist daily plan 할일 체크리스트 숙제'})

def info():
    about=f'''<p>{t('Daeva Atlas is an independent, AI-assisted AION 2 guide project maintained by GitHub user bumblev95. Its purpose is to help English-speaking and Korean-speaking readers make sense of class choices and the context around game advice. It is not an official NC publication.','Daeva Atlas는 GitHub 사용자 bumblev95가 관리하는 AI 도움을 받아 제작한 독립 아이온 2 가이드 프로젝트입니다. 영어·한국어 독자가 직업 선택과 공략의 맥락을 이해하도록 돕습니다. NC 공식 간행물이 아닙니다.')}</p><h2>{t('What we publish','제공하는 내용')}</h2><p>{t('Our launch collection combines sourced orientation with original decision frameworks and practical browser tools. Class comparisons describe playstyle trade-offs. They do not claim live damage testing, professional player credentials, or privileged access to the game.','초기 가이드는 출처를 확인한 안내, 독자적인 판단 방법, 브라우저 도구로 구성됩니다. 직업 비교는 플레이스타일의 고려 사항을 설명합니다. 실제 피해량 측정, 전문 플레이어 경력, 게임의 비공개 정보 접근을 주장하지 않습니다.')}</p><h2>{t('Three labels we keep separate','구분하는 세 가지 정보')}</h2><ul><li>{t('Official fact: a narrow claim linked to a publisher source.','공식 사실: 제작사 출처가 뒷받침하는 구체적인 주장.')}</li><li>{t('Editorial advice: an explanation, exercise or decision method developed for this guide.','편집 조언: 이 가이드를 위해 작성한 설명, 연습법, 판단 방법.')}</li><li>{t('Unverified detail: something we cannot currently substantiate. We omit numerical recommendations when their evidence is missing.','미확인 정보: 현재 입증하지 못한 내용. 근거가 부족한 수치 추천은 제외합니다.')}</li></ul><h2>{t('Updates and corrections','수정과 업데이트')}</h2><p>{t('Review dates reflect a content review, not a live connection to the game. We update dates when we review the actual substance. A Korean balance change does not automatically become a global recommendation. Readers can submit a source or correction through the public issue tracker.','검토 날짜는 내용 확인 시점을 뜻하며 게임에 실시간 연결되었다는 의미가 아닙니다. 실제 내용을 검토했을 때 날짜를 바꿉니다. 한국 밸런스 변경을 곧바로 글로벌 추천으로 적용하지 않습니다. 공개 이슈 게시판에서 출처나 수정 요청을 제출할 수 있습니다.')}</p><h2>{t('Funding','운영과 광고')}</h2><p>{t('The site is free to read. Advertising may support its operation after the relevant account, site and consent setup is complete. No payment changes our class descriptions. At this release, advertising and analytics scripts are disabled.','사이트는 무료로 읽을 수 있습니다. 계정·사이트·동의 설정이 완료되면 광고가 운영을 지원할 수 있습니다. 금전 제공이 직업 설명을 바꾸지는 않습니다. 이번 배포에서는 광고와 방문 분석 스크립트가 꺼져 있습니다.')}</p>'''
    privacy=f'''<p>{t('Effective October 7, 2026. This notice describes this release of Daeva Atlas.','시행일: 2026년 10월 7일. 현재 배포된 Daeva Atlas의 데이터 처리를 설명합니다.')}</p><h2>{t('What the website stores','사이트가 저장하는 정보')}</h2><p>{t('The planner saves task text and completion state in your browser’s local storage under daeva-atlas-planner-v1. We do not upload that list to a server. It persists until you clear it or clear browser storage, and it does not sync between devices. Avoid putting private account information in a task.','플래너는 할 일과 완료 여부를 브라우저의 daeva-atlas-planner-v1 로컬 저장소에 저장합니다. 목록을 서버에 업로드하지 않습니다. 직접 삭제하거나 브라우저 데이터를 지울 때까지 남으며 기기 간 동기화되지 않습니다. 할 일에 비공개 계정 정보를 적지 마세요.')}</p><button class="btn" data-clear-local>{t('Delete my saved planner','저장된 플래너 삭제')}</button><p class="status" data-clear-status role="status"></p><h2>{t('Hosting and external links','호스팅과 외부 링크')}</h2><p>{t('GitHub Pages delivers this website and may process request information such as IP addresses and access logs under GitHub’s own policies. When you follow a link to NC, Steam, GitHub or another website, that service handles your visit under its policies. All fonts and decorative illustrations used by this site are local or system resources.','GitHub Pages가 사이트를 제공하며 GitHub 자체 정책에 따라 IP 주소와 접속 기록 같은 요청 정보를 처리할 수 있습니다. NC, Steam, GitHub 등 외부 링크로 이동하면 해당 서비스의 정책이 적용됩니다. 이 사이트의 글꼴과 장식 이미지는 기기 기본 자원 또는 자체 파일을 사용합니다.')}</p><p><a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub General Privacy Statement ↗</a></p><h2>{t('Advertising and analytics','광고와 방문 분석')}</h2><p>{t('This release does not load AdSense, Google Analytics or third-party ad tracking. Before advertising or analytics is enabled, this notice must be updated to describe the services and choices actually offered. A generic cookie banner is not a substitute for the consent management required by an advertising provider.','현재 배포에서는 AdSense, Google Analytics, 외부 광고 추적 스크립트를 불러오지 않습니다. 광고나 분석을 켜기 전에는 실제 서비스와 선택 방법에 맞게 이 안내를 수정해야 합니다. 단순 쿠키 배너만으로 광고 업체가 요구하는 동의 관리를 대신할 수는 없습니다.')}</p><h2>{t('Contact','문의')}</h2><p>{t('For site or privacy questions, use the project issue tracker. GitHub issues are public; do not include passwords, account identifiers, payment details or other private information. A GitHub account is required to submit an issue.','사이트·개인정보 관련 질문은 프로젝트 이슈 게시판을 이용하세요. GitHub 이슈는 공개되므로 비밀번호, 계정 식별 정보, 결제 내용 등 비공개 정보를 적지 마세요. 이슈 작성에는 GitHub 계정이 필요합니다.')}</p><p><a href="{REPO}/issues">{t('Open the issue tracker','이슈 게시판 열기')} ↗</a></p>'''
    contact=f'''<p>{t('Found an outdated detail, a broken page or a translation that misses the meaning? Send a clear correction through our GitHub issue tracker. This is the site’s current contact channel.','오래된 정보, 깨진 페이지, 의미가 맞지 않는 번역을 발견했다면 GitHub 이슈로 알려주세요. 현재 사이트의 문의 창구입니다.')}</p><p><a class="btn primary" href="{REPO}/issues/new?template=correction.yml">{t('Report a correction ↗','수정 요청하기 ↗')}</a></p><h2>{t('What helps us verify a correction','확인에 도움이 되는 내용')}</h2><ol><li>{t('The guide URL and the sentence that needs changing.','수정할 공략 주소와 문장.')}</li><li>{t('Your game region, the relevant update date and the activity.','게임 지역, 관련 업데이트 날짜, 콘텐츠.')}</li><li>{t('A public official source, or a clear description of a reproducible observation.','공개 공식 출처 또는 반복 확인할 수 있는 관찰 설명.')}</li></ol><p>{t('GitHub requires an account to submit issues, and reports are public. Please do not share credentials, payment details or private screenshots. Game account or billing support belongs with NC, not this fan project.','이슈 작성에는 GitHub 계정이 필요하며 내용은 공개됩니다. 로그인 정보, 결제 내용, 비공개 스크린샷을 올리지 마세요. 게임 계정·결제 지원은 이 팬 프로젝트가 아닌 NC에 문의해야 합니다.')}</p>'''
    terms=f'''<p>{t('Daeva Atlas provides educational game commentary and planning tools. It is an independent fan publication and is not endorsed by NC. AION 2, class names and related trademarks belong to their respective owners.','Daeva Atlas는 게임 해설과 계획 도구를 제공하는 독립 팬 프로젝트이며 NC의 인증을 받지 않았습니다. 아이온 2, 직업명과 관련 상표의 권리는 각 권리자에게 있습니다.')}</p><h2>{t('Using a guide','공략 이용 안내')}</h2><p>{t('Game rules, availability and balance change. Check the current official notice and in-game text before making a decision involving money, limited resources or account changes. Editorial advice does not guarantee a result. The planner is a personal organisational tool, not an automated game client.','게임 규칙, 이용 가능 범위, 밸런스는 바뀔 수 있습니다. 금전, 한정 재화, 계정 변경과 관련한 결정 전에는 최신 공식 공지와 게임 안의 설명을 확인하세요. 편집 조언이 결과를 보장하지는 않습니다. 플래너는 개인 정리 도구이며 게임 자동화 프로그램이 아닙니다.')}</p><h2>{t('Attribution and artwork','출처와 일러스트')}</h2><p>{t('Our articles link to their sources and use original explanations. The decorative atlas landscape and class symbols are original illustrations, not screenshots or representations of exact game locations or official skill icons. Linking to a source does not imply a partnership.','글에는 출처 링크와 직접 작성한 설명을 제공합니다. 장식용 풍경과 직업 기호는 직접 제작한 일러스트이며 실제 게임 장소의 정확한 모습이나 공식 스킬 아이콘이 아닙니다. 출처 링크가 제휴 관계를 의미하지는 않습니다.')}</p><h2>{t('Corrections','수정 요청')}</h2><p>{t('If you believe content is inaccurate or infringes your rights, identify the page and the issue through the contact channel. Do not repost other creators’ full guides into a public report.','정보 오류나 권리 침해가 있다고 판단되면 문의 창구에서 해당 페이지와 문제를 알려주세요. 다른 제작자의 전체 공략을 공개 이슈에 재게시하지 마세요.')}</p>'''
    sourcebody=f'''<p>{t('This is a curated source register, not a live news feed. The current guide collection was reviewed on October 7, 2026. We do not publish a new “updated” date simply because the website was rebuilt.','실시간 뉴스 피드가 아닌 출처 목록입니다. 현재 가이드의 검토일은 2026년 10월 7일입니다. 사이트를 다시 빌드했다는 이유만으로 검토 날짜를 바꾸지 않습니다.')}</p><h2>{t('The source register','출처 목록')}</h2>{sourcelist(list(SOURCES))}<h2>{t('Publication log','발행 기록')}</h2><p><strong>2026-10-07 · {t('First edition','첫 번째 버전')}</strong><br>{t('Published six editorial guides, eight class profiles, a class comparison tool, a bilingual glossary and a browser-local planner. Ads and analytics remain disabled. No live combat benchmarks have been published.','편집 가이드 6개, 직업 프로필 8개, 직업 비교, 한영 용어집, 브라우저 플래너를 공개했습니다. 광고·분석 스크립트는 꺼져 있으며 실제 전투 벤치마크는 공개하지 않았습니다.')}</p>'''
    for sub,title,desc,body in [
        ('about/',t('About Daeva Atlas','Daeva Atlas 소개'),t('An independent guide with visible sources and clear editorial boundaries.','출처와 편집 범위를 명확하게 설명하는 독립 가이드.'),about),
        ('privacy/',t('Privacy & local data','개인정보와 기기 저장'),t('What this release stores and how to delete your saved planner.','현재 버전이 저장하는 정보와 플래너 삭제 방법.'),privacy),
        ('contact/',t('Contact & corrections','문의와 수정 요청'),t('Help make the guide more useful with a source-backed correction.','출처가 있는 수정 요청으로 가이드의 품질을 높여주세요.'),contact),
        ('terms/',t('Terms & disclaimer','이용 안내와 면책'),t('How to use this independent fan guide.','독립 팬 가이드의 이용 안내.'),terms),
        ('sources/',t('Sources & publication log','출처와 발행 기록'),t('The evidence behind this edition, and what has actually changed.','이번 버전의 정보 출처와 실제 변경 내용을 확인하세요.'),sourcebody)]:
        write(sub,title,desc,f'<div class="wrap">{pagehead(title,desc)}<div class="prose">{body}</div></div>')

def searchpage():
    content=f'''<div class="wrap">{pagehead(t('What are you looking for?','어떤 정보가 궁금한가요?'),t('Search class names in English or Korean, guide topics and planning tools.','영어·한국어 직업명, 공략 주제, 플레이 도구를 검색하세요.'))}<form data-search-form role="search"><label class="sr-only" for="site-search">{t('Search all guides','모든 공략 검색')}</label><div class="searchbox">{icon('search')}<input id="site-search" data-site-search type="search" name="q" placeholder="{t('Class, PvP, Korean guide…','직업, PvP, 한국 공략…')}" autocomplete="off"><button type="submit" class="btn">{t('Search','검색')}</button></div></form><p class="small muted" data-search-status role="status">{t('Loading search…','검색 준비 중…')}</p><div class="search-results" data-search-results></div><noscript><p>{t('Search needs JavaScript. Browse all articles in the guide library.','검색에는 자바스크립트가 필요합니다. 공략 모음에서 모든 글을 확인하세요.')}</p>{link('guides/',t('Browse guides','공략 보기'),'btn')}</noscript></div>'''
    write('search/',t('Search AION 2 guides','아이온 2 공략 검색'),t('Search Daeva Atlas guides and tools.','Daeva Atlas의 공략과 도구를 검색하세요.'),content,index=False)

def build():
    global L,LANG
    if OUT.exists():shutil.rmtree(OUT)
    OUT.mkdir();shutil.copytree(ROOT/'assets',OUT/'assets')
    for L,LANG in enumerate(['en','ko']):
        home();guides();classes();compare();glossary();planner();info();searchpage()
    (OUT/'search-index.json').write_text(json.dumps(search_index,ensure_ascii=False,separators=(',',':')))
    (OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+E(url)+'</loc><lastmod>'+REVIEWED+'</lastmod></url>' for url in pages)+'</urlset>')
    (OUT/'.nojekyll').write_text('')
    (OUT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+SITE+'/sitemap.xml\n')
    if valid_pub:(OUT/'ads.txt').write_text('google.com, '+ads['publisher_id'].removeprefix('ca-')+', DIRECT, f08c47fec0942fa0\n')
    L=0;LANG='en'
    (OUT/'404.html').write_text(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found | Daeva Atlas</title><meta name="robots" content="noindex"><link rel="stylesheet" href="{BASE}assets/style.css"></head><body><main class="wrap"><div class="page-head"><div class="eyebrow">Daeva Atlas · 404</div><h1>This path leads elsewhere.</h1><p>The guide you requested could not be found.</p>{button("","Back to the field guide",True)}</div></main></body></html>')
    print(f'Built {len(pages)} indexable pages + 2 search pages and 404; {len(search_index)} search entries.')
if __name__=='__main__':build()
