"""Original editorial copy. Facts and editorial advice are intentionally separate."""

SOURCES = {
 'launch': {'title':'NC — AION 2 global PC launch announcement', 'date':'2026-10-05', 'url':'https://www.nc.com/newsroom/news/articles/?articleId=6ac39f50fa34c1011d627aa7&boardLanguage=en', 'scope':'Global', 'note':'Publisher announcement of the October 5, 2026 PC launch. Not a balance or performance source.'},
 'core': {'title':'NC — AION 2 core content reveal', 'date':'2025-05-29', 'url':'https://www.nc.com/newsroom/news/articles/?articleId=6838f5000000000000001787&boardLanguage=en', 'scope':'Historical design baseline', 'note':'Early class identity descriptions. Older terminology and system details may differ from the current client.'},
 'official': {'title':'AION 2 — official global website', 'date':'2026-10-07', 'url':'https://aion2.plaync.com/en-us/index', 'scope':'Global', 'note':'Official entry point for current notices. This site does not mirror live server status.'},
 'steam': {'title':'AION 2 — official Steam store', 'date':'2026-10-07', 'url':'https://store.steampowered.com/app/3393110/AION_2/', 'scope':'Global PC', 'note':'Check region availability, current requirements and store terms on the publisher’s listing.'},
}

# These are qualitative playstyle groupings, not tested DPS, difficulty or tier scores.
CLASSES = [
 {'id':'gladiator','en':'Gladiator','ko':'검성','role':'damage','range':'melee','icon':'swords','color':'#ad622e',
  'line':['Lead with the blade.','전선에서 시작하는 전투.'], 'identity':['Broad melee offence','광역 근접 공격'],
  'fit':['You enjoy fighting near enemies and choosing when to commit.','적과 가까이 싸우며 공격에 들어갈 타이밍을 고르는 플레이.'],
  'trade':['Close range makes positioning and an exit route part of your damage plan.','근접 전투에서는 공격 위치와 빠져나올 경로도 중요합니다.'],
  'practice':['Repeat one short encounter. Notice when you stop attacking to move; aim to reduce unnecessary movement before chasing a longer combo.','같은 짧은 전투를 반복하며 이동 때문에 공격이 끊기는 순간을 확인하세요. 긴 연계보다 불필요한 이동을 먼저 줄여보세요.']},
 {'id':'templar','en':'Templar','ko':'수호성','role':'tank','range':'melee','icon':'shield','color':'#3c7490',
  'line':['Be the steady centre.','파티의 중심을 지키세요.'], 'identity':['Defensive frontline','방어 중심의 전선'],
  'fit':['You like watching enemy direction and helping a group stay organised.','적의 방향과 파티의 위치를 살피며 전투를 정리하는 플레이.'],
  'trade':['A durable character still needs mechanic knowledge; survivability does not automatically make leading a party easy.','생존력이 있어도 패턴 이해는 필요합니다. 튼튼하다고 파티를 이끄는 역할까지 쉬워지는 것은 아닙니다.'],
  'practice':['Pick a safe facing direction before a pull. After it ends, check whether your movement forced teammates to reposition.','전투 전에 적을 바라보게 할 방향을 정하세요. 전투 후 내 이동 때문에 파티원까지 자리를 옮겼는지 돌아보세요.']},
 {'id':'assassin','en':'Assassin','ko':'살성','role':'damage','range':'melee','icon':'dagger','color':'#8b5c76',
  'line':['Choose your moment.','결정적인 순간을 고르세요.'], 'identity':['Precision melee','정교한 근접 전투'],
  'fit':['You enjoy short attack windows, target selection and close control of movement.','짧은 공격 기회, 대상 선택, 섬세한 이동 조작을 즐기는 플레이.'],
  'trade':['A burst opportunity is less useful if you cannot disengage afterwards. Practise an exit as deliberately as an opener.','순간 공격 이후 빠져나오지 못하면 기회를 살리기 어렵습니다. 진입만큼 이탈도 연습하세요.'],
  'practice':['Before engaging, name one reason to attack and one reason to retreat. Review whether you actually followed those conditions.','진입 전에 공격할 조건과 물러날 조건을 하나씩 정하세요. 실제 전투에서 그 조건을 지켰는지 확인하세요.']},
 {'id':'ranger','en':'Ranger','ko':'궁성','role':'damage','range':'ranged','icon':'bow','color':'#527849',
  'line':['Make distance matter.','거리를 유리하게 쓰세요.'], 'identity':['Physical ranged combat','물리 원거리 전투'],
  'fit':['You like managing distance and keeping a clear view of the encounter.','거리를 조절하고 전장의 전체 상황을 보는 플레이.'],
  'trade':['Standing far away can separate you from support or the next mechanic. Range is a tool, not a reason to ignore the group.','너무 멀리 떨어지면 지원이나 다음 기믹에 대응하기 어렵습니다. 사거리와 파티 위치를 함께 보세요.'],
  'practice':['Choose two safe positions before a pull. Move between them without losing sight of your target or blocking your own escape.','전투 전에 안전한 위치 두 곳을 정하세요. 대상을 놓치거나 퇴로를 막지 않고 오가는 연습을 해보세요.']},
 {'id':'sorcerer','en':'Sorcerer','ko':'마도성','role':'damage','range':'ranged','icon':'spark','color':'#7864a5',
  'line':['Turn space into power.','공간을 공격 기회로 바꾸세요.'], 'identity':['Burst magic','순간 마법 공격'],
  'fit':['You enjoy planning an offensive sequence around a safe damage window.','안전한 공격 시간을 확보하고 마법 연계를 계획하는 플레이.'],
  'trade':['A perfect sequence on a stationary target may be impractical in a moving encounter. Learn a shorter sequence you can finish safely.','움직이지 않는 대상에게 좋은 연계도 실전에서는 어렵습니다. 안전하게 끝낼 수 있는 짧은 연계도 익혀두세요.'],
  'practice':['Separate a safe opening from your full sequence. Track interrupted attempts and unnecessary damage taken, not just the largest hit.','안전한 시작과 전체 연계를 나누세요. 가장 큰 피해량뿐 아니라 도중에 끊긴 횟수와 피할 수 있던 피해도 기록하세요.']},
 {'id':'spiritmaster','en':'Spiritmaster','ko':'정령성','role':'damage','range':'ranged','icon':'flame','color':'#a5664d',
  'line':['Fight with a second presence.','정령과 함께 전투를 만드세요.'], 'identity':['Summoning-oriented play','정령을 활용하는 전투'],
  'fit':['You enjoy managing your own position while paying attention to an additional combat presence.','자신의 위치와 정령의 상태를 함께 살피는 플레이.'],
  'trade':['Summoning does not remove the need to understand targeting and encounter mechanics. Verify the current command behaviour yourself.','정령이 있어도 대상 지정과 기믹 이해는 필요합니다. 현재 버전의 명령 동작을 직접 확인하세요.'],
  'practice':['Try changing targets and moving around terrain in a low-risk fight. Watch what the summon does before relying on it in a group encounter.','부담이 적은 전투에서 대상을 바꾸고 지형을 돌아보세요. 파티 전투에 들어가기 전에 정령의 반응을 관찰하세요.']},
 {'id':'cleric','en':'Cleric','ko':'치유성','role':'healer','range':'ranged','icon':'cross','color':'#558b80',
  'line':['Keep the next pull alive.','파티의 다음 기회를 지키세요.'], 'identity':['Healing-focused support','회복 중심의 지원'],
  'fit':['You like watching the whole party and choosing who needs help first.','파티 전체를 살피며 누구를 먼저 도울지 판단하는 플레이.'],
  'trade':['Healing responsibility includes positioning and prioritisation. It is not a guarantee of instant groups or an effortless solo route.','회복 역할에는 위치 선정과 우선순위 판단이 필요합니다. 빠른 파티 모집이나 쉬운 솔로 플레이가 보장되지는 않습니다.'],
  'practice':['Make party status easy to read. In a familiar encounter, practise staying safe while identifying the next teammate likely to need help.','파티 상태를 잘 보이게 설정하세요. 익숙한 전투에서 자신의 안전을 지키며 다음에 도움이 필요한 사람을 예상해보세요.']},
 {'id':'chanter','en':'Chanter','ko':'호법성','role':'support','range':'melee','icon':'staff','color':'#9a803c',
  'line':['Make the party stronger.','파티의 힘을 더하세요.'], 'identity':['Versatile party support','다양한 파티 지원'],
  'fit':['You enjoy balancing your own attacks with the needs of nearby teammates.','자신의 공격과 주변 파티원의 필요 사이에서 균형을 잡는 플레이.'],
  'trade':['A flexible kit is not automatically a substitute for every specialist. Agree on your actual responsibility before the encounter.','다양한 능력이 모든 전문 역할을 대신한다는 뜻은 아닙니다. 전투 전에 자신이 맡을 일을 확인하세요.'],
  'practice':['Write down your first responsibility for the next pull. Afterwards, check whether chasing personal damage distracted you from it.','다음 전투에서 맡을 첫 번째 역할을 정하세요. 개인 피해량을 올리느라 그 역할을 놓쳤는지 돌아보세요.']},
]

GUIDES = [
 {'slug':'choose-your-class','category':['Classes','직업 선택'],'minutes':7,'title':['Which AION 2 class should you play?','아이온 2, 나에게 맞는 직업 고르기'],'description':['Choose by the decisions you enjoy making, then compare your shortlist with a repeatable trial.','좋아하는 전투 방식으로 후보를 좁히고, 같은 조건에서 비교하는 방법.'],'scope':['Playstyle advice · Global & KR','플레이스타일 조언 · 글로벌·한국'],'sources':['core','official'],'sections':[
  (['Start with your job, not a letter grade','티어보다 하고 싶은 역할부터'],['A useful first choice is the responsibility you want in a fight. Templars suit interest in the frontline, Clerics in healing, and Chanters in supporting a party. Damage-oriented choices then split into close-range and ranged styles. These are orientation labels drawn from class identities, not a ranking of current balance. A class can feel comfortable in one activity and demanding in another.','첫 선택은 전투에서 맡고 싶은 책임으로 시작하는 것이 좋습니다. 전선을 지키는 역할은 수호성, 회복은 치유성, 파티 지원은 호법성부터 살펴보세요. 공격 위주의 후보는 근접과 원거리로 나누면 비교가 쉬워집니다. 이 분류는 직업의 방향을 설명하며 현재 밸런스 순위는 아닙니다. 같은 직업도 어떤 콘텐츠를 하느냐에 따라 난도가 달라집니다.']),
  (['Build a two-class shortlist','후보를 두 직업으로 좁히세요'],['Compare one familiar option with one that genuinely interests you. Gladiator versus Assassin asks whether you prefer sustained frontline involvement or precise engagements. Ranger versus Sorcerer asks whether physical ranged combat or a magic-focused sequence appeals more. Cleric versus Chanter is a question about primary responsibility, rather than which is universally better. Include Spiritmaster if summon management itself sounds enjoyable. Avoid levelling all eight just to postpone a decision.','익숙한 방향 하나와 끌리는 방향 하나를 비교하세요. 검성과 살성은 전선에 오래 머무르는 방식과 정교하게 진입하는 방식의 차이를 생각하면 좋습니다. 궁성과 마도성은 물리 원거리와 마법 연계 중 어느 쪽이 더 즐거운지 살펴보세요. 치유성과 호법성은 누가 더 좋으냐보다 맡고 싶은 책임이 무엇인지가 중요합니다. 정령을 다루는 과정이 재미있어 보인다면 정령성도 후보에 넣으세요.']),
  (['Use the same trial for both','같은 조건으로 시험하세요'],['Give each candidate a short, comparable session. Use similar progression, equipment and the same available encounter; do not compare a geared main against a fresh alternate. Notice three things: whether you can see important threats, whether the controls feel comfortable, and whether you enjoy the recovery after a mistake. A clean repeated run is more informative than a highlight clip. Record what you disliked as well as what felt powerful.','비슷한 성장 단계와 장비, 같은 종류의 전투에서 비교하세요. 장비가 좋은 본캐와 막 만든 부캐를 비교하면 직업보다 투자 차이를 보게 됩니다. 위험이 잘 보이는지, 조작이 편한지, 실수 뒤 다시 대응하는 과정이 재미있는지를 확인하세요. 멋진 장면 한 번보다 안정적으로 반복할 수 있는 전투가 더 유용한 판단 자료입니다. 강했던 순간뿐 아니라 불편했던 점도 적어두세요.']),
  (['Match the class to your actual week','실제 플레이 시간을 기준으로'],['If most sessions are short and solo, test solo comfort first. If you have a regular group, discuss missing responsibilities and schedules before rerolling. For PvP, identify whether you mean duels, small groups or larger fights; those contexts ask different questions. Do not treat an unlabelled PvP tier list as a universal answer. The comparison tool below deliberately uses roles and range rather than unsupported damage scores.','대부분 짧게 혼자 플레이한다면 솔로 조작감을 먼저 확인하세요. 고정 파티가 있다면 직업을 바꾸기 전에 필요한 역할과 접속 시간을 맞춰보세요. PvP도 결투, 소규모, 대규모 전투를 나눠 생각해야 합니다. 조건을 적지 않은 PvP 티어표 하나로 모든 상황을 판단하지 마세요. 이 사이트의 비교 도구도 근거 없는 피해량 점수 대신 역할과 거리를 보여줍니다.']),
  (['What would change this recommendation?','다시 확인해야 할 때'],['Revisit the choice when your preferred activity changes, when a patch substantially alters a mechanic you rely on, or when the controls continue to feel uncomfortable after practice. A small balance change is not by itself a reason to abandon a character. Before following a build from Korea, confirm the skill exists in your client and that its description matches. This guide is editorial decision support; it is not a tested endgame build.','주로 하는 콘텐츠가 바뀌거나, 중요한 기술이 크게 수정되거나, 연습해도 조작이 계속 불편하다면 다시 비교하세요. 작은 수치 변경만으로 캐릭터를 포기할 필요는 없습니다. 한국 빌드를 가져오기 전에는 현재 클라이언트에 같은 기술이 있는지와 설명이 일치하는지 확인하세요. 이 글은 선택을 돕는 조언이며 실측한 최종 세팅은 아닙니다.'])]},
 {'slug':'first-session','category':['Start here','시작 가이드'],'minutes':6,'title':['Your first session: a plan that survives launch week','첫 접속, 무엇부터 해야 할까?'],'description':['A practical order for settings, character choice and your first repeatable gameplay loop.','설정과 직업 선택부터 반복 가능한 첫 플레이 흐름까지.'],'scope':['Beginner workflow · Global & KR','초보 플레이 순서 · 글로벌·한국'],'sources':['launch','official','steam'],'sections':[
  (['Check the service you are entering','접속할 서비스를 먼저 확인'],['NC announced the global PC launch on October 5, 2026. Use the official site or Steam listing to reach the correct client for your region. An old test client, a Korean guide and the global release can describe different things. Before committing to a character, coordinate region, faction and server with anyone you intend to play with. Read the current selection screen and notice rather than assuming a later transfer will solve a mismatch.','NC는 2026년 10월 5일 글로벌 PC 출시를 발표했습니다. 공식 홈페이지나 Steam에서 자신의 지역에 맞는 클라이언트를 확인하세요. 예전 테스트 클라이언트, 한국 공략, 글로벌 서비스는 서로 다른 내용을 설명할 수 있습니다. 함께할 사람이 있다면 캐릭터에 투자하기 전에 지역·종족·서버를 맞추세요. 나중에 이전하면 된다고 가정하기보다 현재 선택 화면과 공지를 먼저 확인하세요.']),
  (['Make the game readable before making it fast','속도보다 읽기 쉬운 화면부터'],['Spend a few minutes on camera sensitivity, text size and the visibility of party information. Place your most frequently needed inputs where you can reach them while moving. Change one setting at a time and revisit it in the same scene. If a performance issue occurs only in crowds, compare the same crowded area rather than judging a change from an empty room. We do not prescribe a universal graphics preset or claim an FPS gain.','카메라 감도, 글자 크기, 파티 정보 위치를 먼저 조절하세요. 이동하면서 자주 사용하는 키를 누를 수 있도록 배치하는 것이 좋습니다. 설정은 한 번에 하나씩 바꾸고 같은 장소에서 비교하세요. 사람이 많은 곳에서만 느려진다면 같은 혼잡 구간에서 확인해야 합니다. 빈 방에서 부드러워졌다고 대규모 전투 성능도 좋아졌다고 볼 수 없습니다. 특정 그래픽 설정의 FPS 향상을 보장하지 않습니다.']),
  (['Follow one progression thread','성장 목표를 하나만 정하세요'],['For the first session, follow the game’s introductory progression until you understand movement, targeting and the menus it has actually unlocked. When a new system appears, read its cost and purpose before spending. Keep a short note of anything unclear and continue with a known objective. Opening every menu notification can consume the whole session without teaching you a useful combat loop.','첫 접속에는 이동, 대상 지정, 실제로 열린 메뉴를 이해할 때까지 게임의 도입부 진행을 따라가세요. 새 시스템이 열리면 비용과 용도를 읽은 뒤 사용하세요. 모르는 것은 짧게 적어두고 이해한 목표부터 이어가는 편이 좋습니다. 메뉴의 알림을 전부 없애려다 보면 전투 흐름을 익히지 못한 채 시간이 끝날 수 있습니다.']),
  (['Delay choices you cannot explain','설명할 수 없는 소비는 미루세요'],['Before opening a choice box or committing a scarce resource, ask what the item does, whether it is restricted to this character, and whether your next objective needs it. These are questions to answer from the current item text; this guide does not assume particular transfer or refund rules. There is little value in copying a veteran’s spending order when your own bottleneck is still learning an encounter.','선택 상자를 열거나 귀한 재료를 쓰기 전에 용도, 캐릭터 제한, 다음 목표에 필요한지부터 확인하세요. 현재 아이템 설명에서 답을 찾아야 하며 이전이나 환불이 가능하다고 가정하지 마세요. 아직 전투 방법을 익히는 단계라면 숙련자의 소비 순서를 그대로 따르는 것이 도움이 되지 않을 수 있습니다.']),
  (['End with a next-session note','다음 접속 메모를 남기세요'],['Finish with one concrete objective: test a different keybind, practise a familiar encounter, or resolve a question about an unlocked system. Use the planner for your own tasks, not as a list of mandatory game dailies. It saves in this browser and has a manual reset, so no unverified regional reset time is silently applied. A small plan you return to is more useful than a long checklist you abandon.','다른 키 배치를 시험하기, 익숙한 전투 연습하기, 열린 시스템의 질문 해결하기처럼 구체적인 목표 하나를 남기세요. 플래너에는 자신의 할 일을 적으면 됩니다. 게임이 요구하는 필수 일일 숙제 목록이 아닙니다. 이 브라우저에 저장되고 직접 초기화하므로 확인하지 않은 지역별 리셋 시간이 적용되지 않습니다. 다시 찾아볼 짧은 계획이 버리는 긴 목록보다 유용합니다.'])]},
 {'slug':'read-korean-guides','category':['KR → Global','한국 → 글로벌'],'minutes':7,'title':['How to use a Korean guide on global servers','한국 공략을 글로벌 서버에 적용하는 법'],'description':['A four-part compatibility check before copying a rotation, build or spending recommendation.','스킬 연계, 세팅, 재화 소비를 따라 하기 전 확인할 네 가지.'],'scope':['Cross-region reading method','지역 간 공략 활용법'],'sources':['core','official'],'sections':[
  (['Keep four labels beside every recommendation','공략 옆에 네 가지 조건을 적으세요'],['Write down region, date, activity and assumptions. Region tells you which service was observed. Date tells you whether later changes may matter. Activity distinguishes solo progression, group PvE and different kinds of PvP. Assumptions include equipment, unlocked systems and party support. A recommendation with none of those labels may still contain a useful idea, but it is a poor instruction to copy exactly.','지역, 날짜, 콘텐츠, 전제를 적으세요. 지역은 관찰한 서비스, 날짜는 이후 변경 가능성, 콘텐츠는 솔로 성장·파티 PvE·각종 PvP를 구분합니다. 전제에는 장비, 해금한 시스템, 파티 지원이 포함됩니다. 이런 조건이 없는 공략에도 좋은 아이디어는 있을 수 있지만 세팅을 그대로 복사하기에는 부족합니다.']),
  (['Translate the mechanic, not just the sentence','문장보다 기술의 의미를 확인'],['Keep the Korean skill or item name alongside the proposed English name until you have matched the in-game description. Similar names are not proof of identical effects. Check the target, activation condition, duration, resource cost and any stated limitation. If the translated recommendation depends on one ambiguous word, stop and resolve that word before spending resources. Our glossary gives ordinary terminology and class-name mappings; it does not claim every live item name.','한국어 기술·아이템 이름을 영어 이름과 함께 남기고 게임 안의 설명을 대조하세요. 이름이 비슷하다고 효과가 같다는 뜻은 아닙니다. 대상, 발동 조건, 지속 시간, 비용, 제한 사항을 확인하세요. 애매한 단어 하나에 추천 전체가 달려 있다면 재화를 쓰기 전에 그 의미부터 해결하세요. 용어집은 일반 용어와 직업명 대응을 제공하며 모든 실제 아이템 이름을 보장하지 않습니다.']),
  (['Separate portable technique from patch-specific numbers','연습법과 패치 수치를 분리'],['A habit such as recording why a pull failed can transfer well across regions. A precise cooldown alignment or damage threshold depends on current values and needs rechecking. Mark the parts of a guide you can practise without investment and try those first. Leave a gear purchase or irreversible choice until the relevant mechanic is confirmed in your client. This preserves the useful idea without importing an unverified budget.','실패 원인을 기록하는 습관은 지역이 달라도 활용하기 좋습니다. 반면 정확한 재사용 시간 조합이나 피해량 기준은 현재 수치에 따라 다시 확인해야 합니다. 투자 없이 연습할 수 있는 부분부터 표시하고 시험하세요. 장비 구매나 되돌리기 어려운 선택은 현재 클라이언트에서 핵심 동작을 확인한 뒤에 하세요. 좋은 아이디어는 가져오되 검증하지 않은 지출까지 따라갈 필요는 없습니다.']),
  (['Run a small A/B check','작게 비교해보세요'],['Keep equipment and encounter conditions as similar as possible. Try your existing approach several times, then change only the proposed mechanic. Record completion, avoidable mistakes and whether the change felt repeatable. A single lucky run cannot establish a better build. If damage measurements are unavailable or inconsistent, say so and judge only what you can observe reliably. Do not turn a personal impression into a universal DPS ranking.','장비와 전투 조건을 최대한 비슷하게 유지하세요. 기존 방법을 여러 번 해본 뒤 제안받은 동작 하나만 바꾸세요. 성공 여부, 피할 수 있던 실수, 반복 가능성을 기록하세요. 운이 좋았던 한 번으로 더 좋은 빌드라고 결론 내리기는 어렵습니다. 피해량을 측정하기 어렵다면 그 한계를 남기고 확실히 관찰한 부분만 비교하세요. 개인의 느낌을 전체 직업 DPS 순위로 바꾸지 마세요.']),
  (['Credit the original and record the gap','출처와 남은 차이를 함께 남기세요'],['When sharing your conclusion, link the original creator, include the date you tested, and explain exactly what matched or differed. Summarise the useful lesson in your own words rather than republishing the full guide. If the global implementation is unknown, label it unverified. That small piece of missing context is often more valuable to the next reader than another confident tier label.','결과를 공유할 때 원작자 링크와 확인 날짜를 남기고 무엇이 같고 달랐는지 설명하세요. 원문 전체를 다시 올리기보다 배운 점을 자신의 말로 정리하는 것이 좋습니다. 글로벌 적용 여부를 모르겠다면 미확인이라고 표시하세요. 빠진 맥락을 알려주는 일이 확신에 찬 티어 하나를 더 붙이는 것보다 다음 사람에게 유용할 수 있습니다.'])]},
 {'slug':'first-group-dungeon','category':['PvE','파티 PvE'],'minutes':6,'title':['A calmer first group dungeon','첫 파티 던전을 차분하게 준비하는 법'],'description':['Prepare a role, a clear pull plan and a useful way to learn after a wipe.','역할 확인, 전투 준비, 실패 후 점검까지 이어지는 방법.'],'scope':['Group-play practice · No boss-specific claims','파티 연습법 · 보스별 기믹 공략 아님'],'sources':['official'],'sections':[
  (['Prepare for the encounter you actually selected','선택한 던전의 조건을 읽으세요'],['Read the current entry requirements and description inside the game. Do not use a party size or reward table copied from an older regional announcement. Before entering, tell the group if this is your first attempt and ask which mechanics require a specific assignment. Learning groups work better when expectations are explicit; a speed-clear listing may not be the right place for a first look.','게임 안에서 현재 입장 조건과 설명을 읽으세요. 예전 지역 공지에 있던 인원수나 보상표를 그대로 가져오지 마세요. 첫 도전이라면 미리 알리고 담당자를 정해야 하는 기믹이 있는지 물어보세요. 기대하는 목표를 공유한 파티가 배우기 좋습니다. 빠른 클리어를 원하는 모집은 첫 관찰에 맞지 않을 수 있습니다.']),
  (['Give each person one clear priority','각자의 첫 우선순위를 정하세요'],['Discuss who controls the pull, what the support players need from the group, and whether anyone has an assigned mechanic. A class name alone does not settle those responsibilities. If you are dealing damage, identify where you can stand without making support or movement harder. If you are supporting, position for visibility and safety before trying to rescue every avoidable mistake.','누가 전투를 시작하는지, 지원 역할이 파티에 바라는 점은 무엇인지, 특정 기믹 담당자가 있는지 확인하세요. 직업명만으로 모든 역할이 정해지는 것은 아닙니다. 공격 역할은 지원과 이동을 방해하지 않는 위치를 찾으세요. 지원 역할은 모든 실수를 수습하려 하기 전에 시야와 자신의 안전을 확보하세요.']),
  (['Use the first pull to read the fight','첫 전투는 패턴을 읽는 시간'],['Watch for a repeated cue, then connect it to the consequence. Identify which movement was necessary and which was panic. Do not invent a boss rule from a single coincidence: ask the party or compare the next occurrence. When a mechanic is not understood, surviving long enough to see it again can teach more than forcing an ambitious damage sequence. This is a learning method, not a substitute for a verified boss guide.','반복되는 신호를 보고 그 뒤의 결과와 연결하세요. 꼭 필요했던 이동과 당황해서 했던 이동을 구분해보세요. 한 번 우연히 일어난 일로 보스 규칙을 만들지 말고 파티에 묻거나 다음 상황과 비교하세요. 이해하지 못한 패턴이 있다면 무리한 공격보다 다시 볼 때까지 생존하는 편이 도움이 됩니다. 이 방법은 학습 과정이며 검증된 보스별 공략을 대신하지 않습니다.']),
  (['Review a wipe without a blame spiral','실패 후 하나만 바꾸세요'],['Name the earliest observable problem, not just the final death. Was someone out of position before the dangerous sequence? Was an assignment unclear? Did the group attempt too much at once? Pick one adjustment for the next pull and leave everything else stable. Changing every skill, position and assignment together makes it difficult to learn which change mattered.','마지막 사망 장면보다 처음 관찰된 문제를 찾으세요. 위험한 패턴 전에 위치가 어긋났는지, 담당이 불분명했는지, 한 번에 너무 많은 것을 하려 했는지 살펴보세요. 다음 전투에서는 한 가지만 바꾸고 다른 조건은 유지하세요. 기술과 위치와 담당을 모두 바꾸면 무엇이 효과가 있었는지 알기 어렵습니다.']),
  (['Take home a reusable note','다음에도 쓸 수 있는 메모'],['Save the encounter name, region, difficulty, date and one concrete lesson. Separate an observed mechanic from something a teammate guessed. A note such as “move earlier when the cue appears” is useful only when you also know which cue. Over several sessions, your own small collection of reproducible observations becomes more valuable than an unfiltered list of tips.','던전 이름, 지역, 난도, 날짜, 구체적인 교훈 하나를 남기세요. 직접 확인한 패턴과 파티원이 추측한 내용을 구분하세요. 신호가 나오면 빨리 움직이라는 메모는 어떤 신호인지 함께 적어야 쓸 수 있습니다. 재현 가능한 관찰을 조금씩 모으면 정리하지 않은 팁 목록보다 유용해집니다.'])]},
 {'slug':'upgrade-decisions','category':['Progression','성장 판단'],'minutes':6,'title':['Before your next upgrade: find the real bottleneck','다음 강화 전에, 무엇이 막히는지 확인하세요'],'description':['A spending decision framework that begins with the encounter you want to clear.','깨고 싶은 콘텐츠에서 출발하는 재화 사용 판단법.'],'scope':['Decision method · Not a price or success-rate database','판단법 · 가격·강화 확률 데이터 아님'],'sources':['official'],'sections':[
  (['Name the outcome before choosing an item','아이템보다 목표부터 정하세요'],['“Get stronger” is too vague to compare purchases. Use an observable goal: survive a known sequence, meet a displayed entry requirement, or finish an encounter more consistently. If you cannot explain how a purchase helps that goal, postpone it. The purpose of this method is to avoid spending on a number that looks impressive but does not solve your current problem.','강해지고 싶다는 목표만으로는 구매를 비교하기 어렵습니다. 특정 패턴 생존, 화면에 표시된 입장 조건 충족, 더 안정적인 클리어처럼 관찰 가능한 목표를 정하세요. 구매가 그 목표에 어떻게 도움이 되는지 설명할 수 없다면 미뤄도 됩니다. 멋져 보이는 수치를 올리는 것과 지금의 문제를 푸는 것은 다를 수 있습니다.']),
  (['Check execution before paying for power','투자 전에 전투 과정을 점검'],['Look at several recent attempts. If most failures come from the same missed mechanic, practise that mechanic before assuming you need better equipment. If you execute consistently but still miss a clear requirement, an upgrade may be relevant. Keep those diagnoses separate. A damage increase cannot be assumed to compensate for an instant-failure condition or an uncompleted assignment.','최근 시도를 여러 번 돌아보세요. 같은 기믹 실수로 실패한다면 장비보다 해당 패턴을 먼저 연습하세요. 동작은 안정적이지만 명확한 조건을 계속 충족하지 못한다면 투자가 도움이 될 수 있습니다. 두 상황을 나누어 판단하세요. 피해량이 높아지면 모든 실패 조건이나 담당 누락을 해결한다고 가정할 수는 없습니다.']),
  (['Read the full cost in the current client','현재 화면의 전체 비용을 확인'],['Include every displayed currency and material in your comparison, and read any binding, expiry or transfer restrictions. Check whether failure changes the cost before repeating an attempt. This guide supplies no enhancement probability, pity rule or guaranteed upgrade path: those need a current, region-specific source. A copied spreadsheet with the wrong assumptions can be more expensive than no spreadsheet.','표시된 재화와 재료를 모두 포함해 비교하고 귀속, 기간, 이전 제한을 읽으세요. 반복 시도 전에 실패가 비용에 어떤 영향을 주는지도 확인하세요. 이 글은 강화 확률, 천장 규칙, 확정 성장 경로를 제공하지 않습니다. 그런 수치는 현재 지역에 맞는 출처가 필요합니다. 전제가 틀린 계산표를 그대로 쓰면 오히려 손해를 볼 수 있습니다.']),
  (['Choose a stopping rule in advance','멈출 기준을 미리 정하세요'],['Set a resource budget before starting and keep enough for the activities you still want to play. Decide what you will do if the result is not what you hoped: wait, practise, gather more information or choose a different objective. Past spending is not evidence that the next attempt is worthwhile. Do not let a guide, a timer or another player’s equipment set your personal spending limit.','시작 전에 쓸 재료의 범위를 정하고 계속 즐길 활동에 필요한 여유를 남기세요. 원하는 결과가 나오지 않으면 기다릴지, 연습할지, 정보를 더 찾을지, 목표를 바꿀지 미리 정하세요. 이미 쓴 비용이 다음 시도의 가치를 증명하지는 않습니다. 공략, 남은 시간 표시, 다른 사람의 장비가 자신의 지출 한도를 결정하도록 두지 마세요.']),
  (['Recheck the result against the original goal','처음 목표로 돌아가 확인'],['After changing equipment, repeat the same relevant activity and record what improved. If your original problem remains, diagnose it again rather than automatically purchasing the next upgrade. Keep a short record of the decision, expected benefit and observed result. Even a modest upgrade becomes a useful lesson when you can explain why it helped.','장비를 바꾼 뒤 같은 활동을 해보고 무엇이 나아졌는지 기록하세요. 원래 문제가 남아 있다면 다음 장비를 바로 사기보다 원인을 다시 살펴보세요. 선택, 기대한 효과, 실제 결과를 짧게 남겨두세요. 작은 성장이라도 왜 도움이 됐는지 설명할 수 있으면 다음 판단에 쓸 경험이 됩니다.'])]},
 {'slug':'pvp-context','category':['PvP','PvP'],'minutes':5,'title':['Why one PvP tier list cannot answer every question','PvP 티어표 하나로 판단하기 어려운 이유'],'description':['Separate duel comfort, group responsibility and the conditions behind a PvP claim.','1대1 조작감, 파티 역할, 평가 조건을 나눠 보는 방법.'],'scope':['PvP evaluation method','PvP 평가 방법'],'sources':['official'],'sections':[
  (['Define the fight before comparing classes','어떤 싸움인지 먼저 정하세요'],['A duel asks whether you can respond to one opponent. A group fight adds target selection, support, positioning and coordination. A larger fight changes visibility and the cost of overextending. None of these automatically predicts the others. When a tier list says “best at PvP”, look for the activity, region, patch and equipment assumptions before accepting the label.','결투는 한 명의 상대에 대응하는 능력을 봅니다. 파티 전투에는 대상 선택, 지원, 위치, 협력이 더해집니다. 규모가 커지면 시야와 무리한 진입의 위험도 달라집니다. 하나의 결과가 나머지를 자동으로 예측하지 않습니다. PvP 최강이라는 표현을 보면 콘텐츠, 지역, 패치, 장비 조건부터 확인하세요.']),
  (['Evaluate decisions you can repeat','반복할 수 있는 판단을 보세요'],['Notice whether you identify a favourable engagement, keep an escape route and recognise when support is unavailable. Those decisions are useful to review even when you cannot measure damage reliably. A highlight can show a possibility; it does not show how often the player failed before recording it. Look for several comparable attempts, including losses.','유리한 싸움을 고르는지, 퇴로를 남기는지, 지원받을 수 없는 순간을 알아차리는지 보세요. 이런 판단은 피해량 측정이 어려워도 점검할 수 있습니다. 하이라이트는 가능한 장면을 보여주지만 그 전에 얼마나 실패했는지는 알려주지 않습니다. 패배를 포함한 비슷한 조건의 여러 시도를 살펴보세요.']),
  (['Keep the conditions visible','조건을 숨기지 마세요'],['Equipment differences, familiarity with an opponent, network conditions and party coordination can change the outcome. Do not assign the entire result to class balance. If you compare two approaches, keep as many conditions stable as possible and say what you could not control. A limited observation with clear conditions is more useful than a universal claim without them.','장비 차이, 상대에 대한 익숙함, 연결 상태, 파티 협력이 결과를 바꿀 수 있습니다. 결과 전체를 직업 밸런스의 효과로 돌리지 마세요. 두 방법을 비교할 때는 가능한 조건을 유지하고 통제하지 못한 부분을 밝히세요. 조건이 분명한 제한적 관찰이 조건 없는 일반화보다 유용합니다.']),
  (['Use a one-question practice session','한 번에 질문 하나만 연습'],['Choose one question for a short session: am I engaging too early, losing track of support, or staying after the favourable window closes? Review that question after each attempt. Once the behaviour is repeatable, move on to another. The goal is to learn which playstyle suits you and what you can improve, not to produce an invented numeric skill rating.','짧은 시간 동안 질문 하나를 정하세요. 너무 빨리 진입하는지, 지원 위치를 놓치는지, 유리한 시간이 끝나도 남아 있는지 중 하나면 됩니다. 매 시도 후 그 질문을 돌아보세요. 동작이 안정되면 다른 질문으로 옮기세요. 자신에게 맞는 스타일과 개선할 행동을 찾는 과정이지 근거 없는 실력 점수를 만드는 과정은 아닙니다.'])]},
]

GLOSSARY = [
 ('검성','Gladiator','Class name · 직업명'),('수호성','Templar','Class name · 직업명'),('살성','Assassin','Class name · 직업명'),('궁성','Ranger','Class name · 직업명'),('마도성','Sorcerer','Class name · 직업명'),('정령성','Spiritmaster','Class name · 직업명'),('치유성','Cleric','Class name · 직업명'),('호법성','Chanter','Class name · 직업명'),
 ('공략','Guide / strategy','Context decides whether this means an article or a tactic. · 글 또는 전투 방법'),('딜러','Damage dealer / DPS','A role; DPS can also mean damage per second. · 역할과 초당 피해량 구분'),('탱커','Tank','Role shorthand · 역할 표현'),('힐러','Healer','Role shorthand · 역할 표현'),('파티','Party / group','Players grouped together · 함께하는 플레이어'),('레이드','Raid','Group activity; verify the actual mode. · 실제 콘텐츠 종류 확인'),('광역','Area of effect / AoE','An effect covering an area · 범위 효과'),('단일','Single target','One-target context · 한 대상 기준'),('재사용 대기시간','Cooldown','Check the current skill text. · 현재 스킬 설명 확인'),('쿨감','Cooldown reduction','Community abbreviation · 커뮤니티 약어'),('치명타','Critical hit','Exact stat wording may vary. · 실제 능력치 명칭 확인'),('명중','Accuracy / hit','Stat or successful contact, depending on context. · 능력치 또는 적중 의미'),('회피','Evasion / dodge','Stat or an action, depending on context. · 능력치 또는 행동 의미'),('어그로','Aggro / threat','Enemy attention; not necessarily the exact UI term. · 적의 주의·위협'),('기믹','Encounter mechanic','A pattern or rule to handle. · 처리해야 하는 패턴·규칙'),('전멸','Wipe','The group fails the attempt. · 파티 전투 실패'),('귀속','Bound','Read character/account restrictions separately. · 캐릭터·계정 제한 별도 확인'),('강화','Enhancement / upgrade','The system determines the exact meaning. · 실제 시스템에 따라 의미 확인'),('천족','Elyos','Faction name · 종족명'),('마족','Asmodians','Faction name · 종족명'),('본캐','Main character','Your primary character · 주로 플레이하는 캐릭터'),('부캐','Alternate character / alt','Another character you play · 추가 캐릭터'),('숙제','Routine tasks / dailies','Player slang, not a mandatory schedule. · 필수 일정이 아닌 유저 표현'),('무과금','No-spend / F2P player','A spending choice, not a content-access guarantee. · 소비 방식과 이용 범위는 별개')
]
