"""Endgame decision guide linked to the existing, attributed boss collection."""
from html import escape as e
from fieldnotes import BOSSES
from poststory import guide as post_story


def guide(lang,base):
    k=lang=='ko';t=lambda en,ko:ko if k else en;r=base+('ko/' if k else '')
    decisions=[
      (('Cannot enter the activity','입장 조건이 부족할 때'),('Read the selected difficulty’s actual requirements before choosing an equipment investment.','선택한 난이도의 실제 입장 조건을 확인하고, 그 조건을 채우는 장비 투자를 우선합니다.'),'gear/',('Equipment and stats','장비·스탯')),
      (('Repeated deaths or wipes','반복해서 사망하거나 전멸할 때'),('Separate failed mechanics from a survivability issue. Review the cue, safe position and assigned role.','기믹 실패인지 생존 부족인지 구분합니다. 전조·안전 위치·분담 역할을 먼저 정리합니다.'),'dungeons/',('Boss mechanics','보스 패턴')),
      (('Too little damage in the available time','주어진 시간에 피해량이 부족할 때'),('Review missed attack windows and skill conditions, then compare the options that address the remaining gap.','공격하지 못한 시간과 스킬 발동 조건을 먼저 점검하고, 남은 부족분을 보완할 옵션을 비교합니다.'),'skills/',('Skills and builds','스킬·빌드')),
      (('Too many possible upgrades','성장 목표가 너무 많을 때'),('Choose a reachable activity and one upgrade goal. Check its rewards and your available reward entries.','현재 갈 수 있는 콘텐츠와 성장 목표 하나를 연결합니다. 보상 내용과 남은 보상 횟수를 기준으로 일정을 정합니다.'),'endgame/#after-story-repeatable',('Next growth activity','다음 성장 콘텐츠')),
    ]
    rows=''.join(f'<tr><th scope="row">{e(problem[k])}</th><td>{e(action[k])}</td><td><a href="{r}{url}">{e(label[k])} →</a></td></tr>' for problem,action,url,label in decisions)
    bosses=''.join(f'<a class="endgame-boss" href="{r}dungeons/{b["slug"]}/"><span>{e(b["dungeon"][k])}</span><h3>{e(b["name"][k])}</h3><p>{e(b["hook"][k])}</p><b>{t("Pattern guide", "패턴 공략")} →</b></a>' for b in BOSSES)
    return f'''<div class="endgame-guide" data-practical-guide><nav class="stage-switch" aria-label="{t('Guide stage','공략 단계')}"><a href="{r}start/">{t('Early game','초반 공략')} →</a><span aria-current="page">{t('Endgame','엔드게임 공략')}</span></nav><nav class="rpg-guide-nav" aria-label="{t('Your next RPG goal','지금 필요한 공략')}"><a href="#after-story">{t('Growth priorities','내실·성장')}</a><a href="#boss-guides">{t('Boss guides','보스 공략')}</a><a href="{r}gear/#upgrade">{t('Enhance equipment','장비 강화')} →</a></nav>
{post_story(lang,base)}
<section class="reference-section" id="priorities"><div class="start-reference-heading"><h2>{t('Choose the next upgrade by what is blocking you','막힌 지점에 따라 다음 목표 결정')}</h2><p>{t('After the initial progression, entry requirements, execution and equipment efficiency become separate decisions.','초반 육성을 마친 뒤에는 입장 조건, 전투 수행, 장비 효율을 나눠 봐야 합니다.')}</p></div><div class="reference-table"><table><thead><tr><th>{t('Current problem','현재 상황')}</th><th>{t('Priority','우선 판단할 것')}</th><th>{t('Related guide','관련 공략')}</th></tr></thead><tbody>{rows}</tbody></table></div></section>
<section class="reference-section" id="boss-guides"><div class="start-reference-heading"><h2>{t('Dungeon and boss references','던전·보스별 공략')}</h2><p>{t('Choose the boss you will face. Each guide connects the cue, safe position and response to an animation and original KR footage.','잡으려는 보스를 고르세요. 전조·안전 위치·대응 방법을 패턴 애니메이션과 한국어 원본 장면으로 확인할 수 있습니다.')}</p></div><div class="endgame-boss-grid">{bosses}</div><p class="reference-scope">{t('Boss explanations follow the linked KR source guides. Check the difficulty and current regional mechanics before applying them.','보스 설명은 연결된 한국 서버 공략 기준입니다. 실제 참여할 난이도와 현재 서버의 기믹에 맞춰 적용합니다.')}</p></section>
<section class="reference-section" id="investment"><div class="start-reference-heading"><h2>{t('Three checks before further investment','추가 투자 전에 비교할 세 가지')}</h2></div><div class="endgame-investment"><article><h3>{t('What does it solve?','어떤 부족분을 해결하는가')}</h3><p>{t('Name the goal: access to a run, surviving a hit, landing attacks or dealing more damage. Compare options against that goal.','입장 조건·생존·명중·피해량 중 목표를 정한 뒤, 그 목표에 실제로 도움이 되는 옵션끼리 비교합니다.')}</p></article><article><h3>{t('How soon will it be replaced?','곧 교체할 장비인가')}</h3><p>{t('Consider the next item you are pursuing alongside enhancement costs and available resources.','다음에 목표로 하는 장비와 현재 강화 비용을 함께 봅니다. 교체 계획이 가까울수록 이번 투자 범위를 명확히 정합니다.')}</p></article><article><h3>{t('Can you compare the result?','전후 차이를 비교할 수 있는가')}</h3><p>{t('Keep the activity and conditions similar. Changing one element at a time makes the effect easier to interpret.','비슷한 콘텐츠와 조건에서 전후를 비교합니다. 한 번에 한 요소를 바꾸면 무엇이 효과가 있었는지 판단하기 쉽습니다.')}</p></article></div><a class="reference-link" href="{r}gear/#upgrade">{t('Equipment upgrade decisions','장비 강화 판단 기준')} →</a></section>
<section class="reference-section" id="party-prep"><div class="start-reference-heading"><h2>{t('Party preparation','파티 준비')}</h2></div><ul class="endgame-checks"><li>{t('Confirm difficulty, entry requirements, rewards and available entries.','난이도·입장 조건·보상·남은 보상 횟수 확인')}</li><li>{t('Identify assigned positions and the mechanic each member must handle.','위치·기믹 분담과 내 역할 확인')}</li><li>{t('If the encounter has a stagger check, coordinate the timing of relevant skills.','그로기 구간이 있는 전투라면 해당 스킬을 사용할 타이밍 조율')}</li><li>{t('Match the group’s first-run or experienced-run expectations.','초행·숙련 등 파티가 요구하는 진행 방식 확인')}</li></ul><div class="reference-links"><a href="{r}start/?view=settings#field-tips">{t('Settings and recruitment terms','편의 설정·모집글 용어')} →</a><a href="{r}insights/">{t('Player tips by activity','콘텐츠별 유저 팁')} →</a></div></section></div>'''
