"""A short, interactive first-session lesson. All diagrams are teaching examples."""
from html import escape as e

# Title, plain concept, action, result, real-game steps, vocabulary.
LESSONS=[
 ('quest',('Get one task','할 일 하나 받기'),('A quest is a task from the game. It gives you a destination and a reward.','퀘스트는 게임이 주는 심부름이에요. 할 일과 보상이 적혀 있어요.'),('Track Episode','에피소드 추적'),('Your destination is now marked. Follow the selected task.','목적지가 표시됐어요. 이제 선택한 할 일을 따라가면 돼요.'),
 [('Open the quest menu and choose an Episode quest.','게임의 퀘스트 메뉴에서 에피소드를 선택하세요.'),('Read the objective, then use its tracking or destination control.','무엇을 하라는지 읽고 추적·목적지 표시를 누르세요.')],
 [('Episode','에피소드',('The main story. It unlocks areas and systems.','새 지역과 기능을 여는 메인 이야기예요.')),('NPC','NPC',('A character controlled by the game, not another player.','다른 유저가 아니라 게임이 조종하는 인물이에요.'))]),
 ('fight',('Attack, then check your health','공격하고 내 체력 보기'),('The enemy loses HP when you hit it. Your red HP bar is how much damage you can still take.','때리면 적의 생명력(HP)이 줄어요. 내 빨간 HP 막대는 앞으로 버틸 수 있는 양이에요.'),('Use an attack','공격 스킬 사용'),('The enemy lost health. Your MP also fell: some skills spend this resource.','적의 체력이 줄었어요. 내 정신력(MP)도 줄었죠? 일부 스킬은 이 자원을 써요.'),
 [('Find a quest enemy and select it. Use a skill that is in range.','퀘스트에 표시된 적을 선택하고, 닿는 거리에서 공격 스킬을 써보세요.'),('Watch your HP and MP. Move away from danger before continuing.','내 HP와 MP를 보세요. 위험한 공격을 피한 뒤 다시 공격하세요.')],
 [('HP','생명력',('Reaching zero means your character falls.','0이 되면 캐릭터가 쓰러져요.')),('MP','정신력',('A resource used by some skills; some attacks restore it.','일부 스킬의 사용 재료예요. 회복해주는 공격도 있어요.'))]),
 ('dodge',('Move out of the red area','빨간 바닥에서 나오기'),('A colored area can warn where the next hit will land. Watch the ground as well as the enemy.','색칠된 바닥은 다음 공격이 닿을 곳을 알려주기도 해요. 적뿐 아니라 바닥도 보세요.'),('Move to the safe side','안전한 쪽으로 이동'),('You moved before the attack landed. Now attack again.','공격이 터지기 전에 나왔어요. 그다음 다시 공격하면 돼요.'),
 [('Practise moving sideways while keeping the enemy visible.','적이 화면에 보이게 유지하면서 옆으로 움직여보세요.'),('Find your dodge and jump bindings in control settings. Some boss patterns need a jump, not a dodge.','조작 설정에서 내 회피·점프 키를 확인하세요. 점프로 넘어야 하는 보스 공격도 있어요.')],
 [('Telegraph','장판·전조',('A warning of an incoming attack. Not every attack has one.','곧 올 공격을 미리 보여주는 표시예요. 모든 공격에 있는 건 아니에요.')),('Cooldown','재사용 시간',('The wait before you can press the same skill again.','같은 스킬을 다시 누를 수 있을 때까지 기다리는 시간이에요.'))]),
 ('reward',('Finish and collect the reward','완료하고 보상 받기'),('Doing the task and collecting its reward are separate steps. The next quest may wait for that reward.','심부름을 끝내는 것과 보상을 받는 것은 별개예요. 보상을 받아야 다음 이야기가 열리기도 해요.'),('Claim the quest reward','퀘스트 보상 받기'),('EXP grows your character level. Gear goes into your inventory.','경험치는 캐릭터 레벨을 올려줘요. 받은 장비는 가방에서 확인해요.'),
 [('Return to the marked destination or open the completed quest.','표시된 보고 장소로 가거나 완료된 퀘스트를 여세요.'),('Confirm the reward and check that the next Episode objective appears.','보상을 받고 다음 에피소드 목표가 생겼는지 확인하세요.')],
 [('EXP','경험치',('Progress toward your next character level.','모으면 캐릭터 레벨이 올라가요.')),('Kinah','키나',('The game’s ordinary money. You use it for several upgrades.','게임의 기본 돈이에요. 여러 성장 메뉴에서도 써요.'))]),
 ('equip',('Put the new item on','새 장비 입기'),('An item sitting in your bag does not strengthen you. Equipment works when it is in its character slot.','가방에만 있는 장비는 나를 강하게 해주지 않아요. 캐릭터의 해당 부위에 착용해야 해요.'),('Equip the new weapon','새 무기 장착'),('The weapon moved to the equipped slot. Check its attack and requirements before replacing the old one.','무기가 착용 칸으로 갔어요. 교체 전에는 공격력과 착용 조건을 비교하세요.'),
 [('Open Inventory and select the quest reward.','가방을 열고 방금 받은 장비를 선택하세요.'),('Compare the same equipment slot, check class restrictions, then choose Equip.','같은 부위의 기존 장비와 비교하고 직업 제한을 확인한 뒤 장착하세요.')],
 [('Item level','아이템 레벨',('A number describing equipment, separate from your character level.','장비의 수준이에요. 내 캐릭터 레벨과는 달라요.')),('Enhancement','강화',('Spending materials to improve an item you own.','이미 가진 장비를 재료를 써서 더 좋게 만드는 거예요.'))]),
 ('skill',('Spend a skill point','스킬 포인트 써보기'),('A skill is an action. A skill point raises that skill. Your character level and the skill’s level are different.','스킬은 캐릭터가 하는 기술이에요. 스킬 포인트로 그 기술을 키워요. 캐릭터 레벨과 스킬 레벨은 달라요.'),('Raise the selected skill','선택한 스킬 레벨 올리기'),('Skill Lv. 1 → 2. The point was spent on this skill, not on your character level.','스킬 레벨이 1 → 2가 됐어요. 캐릭터 레벨이 아니라 이 기술이 성장한 거예요.'),
 [('Open Skills. Pick the class below to see your first two priorities.','게임에서 스킬 메뉴를 여세요. 아래 직업 선택에서 먼저 키울 두 기술을 확인하세요.'),('Select that skill, check the cost and increase its level when allowed.','해당 기술을 고르고 필요한 포인트를 확인한 뒤 올리세요. 잠겨 있으면 표시된 조건을 먼저 채우세요.')],
 [('Passive','패시브',('A learned effect that works without pressing an attack button.','공격 버튼을 누르지 않아도 적용되는 배운 효과예요.')),('Stigma','스티그마',('An extra skill you choose and equip after the system unlocks.','시스템이 열리면 골라 장착하는 추가 기술이에요.'))]),
 ('travel',('Keep a way back','돌아올 거점 챙기기'),('A Kibelisk is a travel point. Find and activate it in the game as your quest takes you past it.','키벨리스크는 이동 거점이에요. 퀘스트 길에 보이면 게임에서 활성화해두세요.'),('Activate this travel point','이동 거점 활성화'),('The stop is checked in this practice. Use the map guide to find real locations.','연습 거점에 확인 표시가 생겼어요. 실제 위치는 지도에서 찾아보세요.'),
 [('Choose Elyos or Asmodian and your current region in our map.','이 사이트 지도에서 천족·마족과 현재 지역을 선택하세요.'),('Select a Kibelisk marker, find it on your in-game map and interact with it.','키벨리스크 마커를 누른 뒤 게임 지도에서 같은 위치를 찾아 상호작용하세요.')],
 [('Faction','진영',('Elyos and Asmodians begin in different regions.','천족과 마족은 시작하는 지역이 달라요.')),('Sealed Dungeon','봉인 던전',('A field activity with permanent-growth materials. Read its entry and reward screen.','성장 재료를 얻는 필드 콘텐츠예요. 입장 조건과 보상을 확인하세요.'))]),
 ('party',('Enter your first party carefully','첫 파티에 들어가기'),('A dungeon is a separate combat area. Party members survive by responding to boss rules together.','던전은 따로 입장하는 전투 공간이에요. 파티원끼리 보스의 규칙에 함께 대응해야 해요.'),('Choose a learning party','초행 가능한 파티 선택'),('Tell the party it is your first run. Watch one boss pattern before entering.','처음이라고 파티에 알려주세요. 입장 전 보스 패턴 하나부터 보고 가세요.'),
 [('Read the dungeon difficulty and entry requirement; choose a group that welcomes first runs.','던전 난이도와 입장 조건을 보고 초행을 받는 파티를 고르세요.'),('Open our boss guide: watch the cue, where you move, and what ends the attack.','보스 가이드에서 전조 → 이동 위치 → 공격이 끝나는 순간을 순서대로 보세요.')],
 [('Tank / healer / damage','탱커·힐러·딜러',('Roles: manage enemy attention, restore allies, or deal damage. Everyone still avoids mechanics.','적의 시선을 관리하거나, 아군을 회복하거나, 피해를 주는 역할이에요. 누구나 기믹은 피해야 해요.')),('Stagger','그로기',('A boss disruption system. Some phases require skills that damage its stagger gauge.','보스를 무력화하는 시스템이에요. 특정 구간에는 그로기 게이지를 깎는 기술이 필요해요.'))]),
]

def tutorial(lang,base):
 t=lambda a,b:b if lang=='ko' else a;r=base+('ko/' if lang=='ko' else '')
 nav=''.join(f'<button data-lesson-pick="{key}" aria-pressed="{str(i==0).lower()}"><span>{i+1:02}</span>{title[lang=="ko"]}<b data-lesson-done="{key}"></b></button>' for i,(key,title,*_) in enumerate(LESSONS))
 panels=''
 for i,(key,title,concept,action,result,steps,vocab) in enumerate(LESSONS):
  extra= '<div class="mock-quest"><b>◆ '+t('EPISODE','에피소드')+'</b><p>'+t('Speak to the marked character','표시된 인물에게 말 걸기')+'</p><small>EXP +　◇ '+t('Quest reward','퀘스트 보상')+'</small></div>'
  if key in ['fight','dodge']:extra='<div class="mock-enemy">♜<span>'+t('ENEMY','적')+'</span><i></i></div><div class="mock-danger"></div><div class="mock-player">'+t('YOU','나')+'</div><div class="mock-hp"><b>HP</b><i></i><b>MP</b><i></i></div>'
  if key=='reward':extra='<div class="mock-loot"><span>✦</span><strong>EXP</strong><span>◇</span><strong>'+t('GEAR','장비')+'</strong><span>◎</span><strong>'+t('KINAH','키나')+'</strong></div>'
  if key=='equip':extra='<div class="mock-bag"><span>'+t('INVENTORY','가방')+'</span><b>⚔</b><i>→</i><span>'+t('EQUIPPED','착용 칸')+'</span><b>□</b></div>'
  if key=='skill':extra='<div class="mock-skill"><span>✦</span><b>'+t('Chosen skill','선택한 기술')+'</b><strong>Lv. <em>1</em></strong><small>'+t('Available points','남은 포인트')+' <em>1</em></small></div>'
  if key=='travel':extra='<div class="mock-travel"><i>◇</i><b>⌖</b><i>◇</i><p>'+t('KIBELISK','키벨리스크')+'</p></div>'
  if key=='party':extra='<div class="mock-party"><span>♜</span><span>✚</span><span>⚔</span><span>✦</span><span>➶</span><p>'+t('FIRST RUN WELCOME','초행 환영')+'</p></div>'
  panels+=f'''<section data-lesson="{key}" {'hidden' if i else ''}><div class="lesson-copy"><span class="section-kicker">LESSON {i+1:02} / 08</span><h2>{title[lang=='ko']}</h2><p>{concept[lang=='ko']}</p></div><div class="lesson-demo" data-demo="{key}"><small>{t('PRACTICE SCREEN · simplified illustration','연습 화면 · 이해를 돕는 예시')}</small><div class="mock-scene">{extra}</div><button class="btn primary" data-lesson-action>{action[lang=='ko']} →</button><p class="lesson-result" data-lesson-result hidden>{result[lang=='ko']}</p></div><div class="real-game"><h3>{t('Now try it in the game','이제 게임에서 해보세요')}</h3><ol>{''.join('<li>'+x[lang=='ko']+'</li>' for x in steps)}</ol></div><div class="lesson-words">{''.join(f'<details><summary>{ko if lang=="ko" else en} <span>?</span></summary><p>{desc[lang=="ko"]}</p></details>' for en,ko,desc in vocab)}</div><button class="btn lesson-next" data-lesson-next>{t('I understand · next','이해했어요 · 다음')} →</button></section>'''
 return f'''<div class="zero-intro"><span class="section-kicker">ABSOLUTE BEGINNER / 8 SMALL STEPS</span><h1>{t('Never played an MMO?<br>Start right here.','MMO가 처음이어도,<br>여기부터 해보세요.')}</h1><p>{t('You get a task, fight, collect rewards, equip them, and learn skills. Let’s try that loop one click at a time.','할 일을 받고 → 싸우고 → 보상을 받고 → 장비와 기술을 키워요. 이 흐름을 한 번씩 눌러보며 익혀볼게요.')}</p></div><section class="first-session" data-tutorial><nav class="lesson-nav" aria-label="{t('Beginner lessons','초보 학습 단계')}">{nav}</nav><div class="lesson-body">{panels}<p class="tutorial-finish" data-tutorial-finish hidden>{t('Ready for the next step. Choose your class and plan your first skill points.','기본 흐름을 익혔어요. 이제 내 직업을 고르고 스킬 포인트 순서를 확인해보세요.')} <a href="{r}skills/">{t('Choose my class','내 직업 고르기')} →</a></p><div class="tutorial-progress"><span data-lesson-progress role="status"></span><button class="text-link" data-lesson-reset>{t('Start over','처음부터')}</button></div></div></section><div class="learning-links"><a href="{r}skills/"><span>✦</span><h2>{t('What should I level?','뭘 찍어야 하나요?')}</h2><p>{t('Your class → skill icons → investment order','내 직업 → 스킬 그림 → 투자 순서')}</p><b>→</b></a><a href="{r}maps/"><span>⌖</span><h2>{t('Where do I go?','어디로 가야 하나요?')}</h2><p>{t('Select a place and see what to do there','장소를 눌러 위치와 할 일 확인')}</p><b>→</b></a><a href="{r}gear/"><span>◇</span><h2>{t('What is this item?','이 아이템은 뭔가요?')}</h2><p>{t('Equipment, stats and materials explained','장비·능력치·재료 구분하기')}</p><b>→</b></a></div>'''
