"""Editorial PvE starting paths. Skill effects are kept separate from advice."""
BUILDS={
 'gladiator':dict(core=['overhead-slam','rending-blow'],next=['ruinous-blow','leaping-slam'],passive=['impact-hit','attack-preparation'],stigma=['lunge-stance','zikels-blessing','rage-burst','focused-block'],why=[('Build your main hit first.','주력 타격의 효과부터 완성해요.'),('Support the attacks you repeat.','자주 반복하는 공격을 함께 키워요.')],picks={'overhead-slam':[5,4,3],'rending-blow':[4,5,3],'ruinous-blow':[1,4,5],'leaping-slam':[1,3,4]},source='6448/31551'),
 'templar':dict(core=['judgment','pummel'],next=['vicious-strike','shield-smite'],passive=['fury','impact-hit-templar'],stigma=['taunt','noble-armor','shield-of-protection','doom-shield'],why=[('Build the repeatable core attack.','전투의 중심이 되는 공격을 키워요.'),('Keep your regular damage sequence useful.','자주 쓰는 연속 공격의 효율을 챙겨요.')],picks={'judgment':[5,4,3],'pummel':[4,5,3],'vicious-strike':[4,5,3],'shield-smite':[3,4]},source='6438/6625'),
 'assassin':dict(core=['heart-gore','quick-slice'],next=['insignia-explosion','ambush'],passive=['rear-smite','exploit-weakness'],stigma=['illusive-clone','swift-contract','triniels-dagger','evasion-stance'],why=[('Learn its critical-hit trigger and reset.','치명타 발동과 재사용 초기화를 익혀요.'),('Build the basic-attack side of the sequence.','연계의 바탕이 되는 기본 공격을 키워요.')],picks={'heart-gore':[5,4,2],'quick-slice':[4,5,3],'insignia-explosion':[5,2,3],'ambush':[2,1,4]},source='6449/17743'),
 'ranger':dict(core=['deadshot','gale-arrow'],next=['snipe','tempest-shot'],passive=['focused-eye','hunters-resolve'],stigma=['vaizels-authority','bow-of-blessing','supporting-fire','griffon-arrow'],why=[('Keep your main shot usable while learning movement.','주력 공격을 이동 대응과 함께 익혀요.'),('Read the buff before adding more damage skills.','공격을 돕는 버프부터 이해해요.')],picks={'deadshot':[3,5,2],'gale-arrow':[5,4,1],'snipe':[4,3],'tempest-shot':[5,3,2]},source='6450/19498'),
 'sorcerer':dict(core=['hellfire','blaze'],next=['firestorm','wish-of-concentration'],passive=['robe-of-flame','fire-mark'],stigma=['element-enhancement','fire-wall','delayed-explosion','cold-storm'],why=[('Mobile casting helps while learning boss movement.','이동 시전으로 보스 공격에 대응하기 쉬워져요.'),('Connect your repeated attacks and buff cycle.','반복 공격과 버프의 흐름을 연결해요.')],picks={'hellfire':[3,5,1],'blaze':[5,3,1],'firestorm':[5,2,4],'wish-of-concentration':[5,4,3]},source='6453/17462'),
 'spiritmaster':dict(core=['combustion','elemental-fusion'],next=['summon-fire-spirit','cold-shock'],passive=['spirit-strike','mental-focus'],stigma=['summon-ancient-spirit','enhance-spirits-benediction','jointstrike-corrode','flame-blessing'],why=[('Invest in the main direct damage skill.','직접 피해를 주는 핵심 기술부터 키워요.'),('Use the elements your spirits accumulate.','정령이 모은 원소를 쓰는 공격을 익혀요.')],picks={'combustion':[5,4,2],'elemental-fusion':[5,2,3],'summon-fire-spirit':[5,2,3],'cold-shock':[3,4]},source='6454/8165'),
 'cleric':dict(core=['condemnation','radiant-recovery'],next=['earths-retribution','healing-light'],passive=['empyrean-lords-grace','healing-enhancement'],stigma=['light-of-protection','earth-punishment','benevolence','summon-resurrection'],why=[('Keep a useful attack for solo questing.','혼자 퀘스트할 때 쓸 공격을 챙겨요.'),('For first parties, learn a group heal early.','첫 파티를 위해 광역 회복도 함께 키워요.')],picks={'condemnation':[5,4,2],'radiant-recovery':[5,2,3],'earths-retribution':[2,5],'healing-light':[4,5,1]},source='6452/7695'),
 'chanter':dict(core=['dark-crush','onslaught'],next=['impactful-crush','recuperation'],passive=['winds-promise','impact-hit-chanter'],stigma=['undefeated-mantra','power-of-the-storm','sprint-mantra','focused-defense'],why=[('Complete the follow-up attack you use often.','자주 쓰는 후속 공격의 효과를 완성해요.'),('Strengthen the repeated basic attack.','반복하는 기본 공격을 함께 키워요.')],picks={'dark-crush':[5,4,3],'onslaught':[4,5,3],'impactful-crush':[3,4],'recuperation':[2,4]},source='6451/22932'),
}
SHEET='https://docs.google.com/spreadsheets/d/1lbHaVairHaz26M8XGNF9CBWqiiHHBM6CylTwNKnlOug/htmlview'
