'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {classify,groups,detailPath}=require('../assets/patchbook.js');
assert.equal(classify([{type:'buff'},{type:'nerf'}]),'adjustment');
assert.equal(classify([{type:'fix'},{type:'tooltip'}]),'fix');
assert.equal(classify([{type:'tooltip'}]),'tooltip');
assert.equal(classify([{type:'buff'},{type:'fix'}]),'buff');
const definitions={templar:{},assassin:{}};
const separate=groups({changes:[{classId:'templar',type:'buff'},{classId:'assassin',type:'nerf'}]},definitions);
assert.deepEqual(separate.map(g=>g.type),['buff','nerf']);
const reviews=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/patch-reviews.json'),'utf8'));
const patch={...reviews['6a9727b8fa34c1011d627551'],id:'6a9727b8fa34c1011d627551',region:'KR'};
assert.equal(groups(patch,definitions).find(g=>g.classId==='templar').type,'adjustment');
assert.equal(detailPath(patch),'updates/kr-6a9727b8fa34c1011d627551/');
assert.throws(()=>detailPath({region:'NA',id:'../escape'}));
assert.throws(()=>detailPath({region:'XX',id:'valid'}));
console.log('PASS: patch badges, real mixed-class changes and stable detail routes.');
